// Placement-parity sprite variants — the declarative table behind the
// Properties panel's read-only "Sprite-specific" variant rows. Many sprite
// Inits read the spawn cell's X/Y parity (pixel bit 4 = 16px-cell LSB) and
// pick a BEHAVIOUR variant; the raw data shows nothing, so the panel surfaces
// the resolved variant (move the sprite one column/row to flip it).
//
// Every mapping here is asm-verified (init + consuming code read; see
// research/notes-sprite-neighbor-dependencies.md Part 4's parity audit).
// VISUAL-ONLY *colour* parity variants (the shy-guy family — Shy Guy / Stilt /
// Woozy / Stretch / Petal Guy / Lantern Ghost — whose spawn-cell X+Y parity
// picks an OBJ palette row) ARE now listed, under the 'Colour' label, because
// the engine renders that palette (SPRITE_PARITY_PALETTE in
// snes-framework/scripts/engine/sprite-parity.ts — asm-derived + v2-validated).
// Still NOT listed: Nep-Enut's skin (a boss, parity → $78,x indirect tileset/
// palette select, not statically rendered). Rotation-direction for the
// auto-spin family ($064/$15E/$1A0/
// $1A1/$101/$102/$144, plus the circling ravens $135/$136) lives in
// canvas/draw/sprite-variant-hints.ts (it carries a calibrated
// rate-sign→clockwise mapping); this table holds everything else, including
// $064's separate Y-parity orbit radius.
//
// The arrow signs $197/$198 also RENDER their parity-selected rotation (the
// engine's PARITY_CEL_VARIANTS in snes-framework/scripts/engine/
// sprite-tile-base.ts picks frame + flip from the same parity), so their
// Direction rows below must stay in lockstep with that table.
//
// `axis: 'xy'` entries index `values` by `2*(y&1) + (x&1)` — matching the asm
// idiom `(Y&$10)>>2 | (X&$10)>>3` (Y parity = high bit; Freezegood, Flyguy,
// hidden cloud, Prince Froggy all use it).
//
// STORAGE RULE (where per-sprite knowledge lives): obj-metadata.json holds the
// BULK, TOOL-GENERATED facts (names, gfx files, cel class, neighborDeps —
// regenerated by pipelines); THIS module holds the small, HAND-AUTHORED,
// asm-curated tables that need types/tuples/comments; canvas/draw holds only
// presentation (glyphs, colours, geometry, the spin-sign calibration). The
// on-outline badges (sprite-variant-hints.ts) DERIVE from this table via the
// helpers below, so the panel and the canvas can never disagree.

export type ParityDirection = 'left' | 'right' | 'up' | 'down'

export interface SpriteParityVariant {
  axis: 'x' | 'y' | 'xy'
  /** Panel field label. 'Direction' is the shared label for the purely
   *  left/right / up-down / mirror category; behavioural variants carry a
   *  specific label. */
  label: string
  /** Value labels: [even, odd] for single-axis; 4 entries indexed by
   *  `2*(y&1)+(x&1)` for 'xy'. */
  values: string[]
  /** Machine-readable directions paralleling `values` ([even, odd]) for the
   *  'Direction' category — drives the on-outline arrow badge
   *  (canvas/draw/sprite-variant-hints.ts). Absent for behavioural variants
   *  and for mirror-only entries with no true side (the boo-guy mace). */
  dirs?: [ParityDirection, ParityDirection]
  /** Spawn-variant badge: when the resolved values-index equals `index`, the
   *  sprite is a continuous `generator` (cyan up-chevron) or spawns a one-shot
   *  `companion` (cyan "+"). Drives the on-outline badge. */
  badge?: { kind: 'generator' | 'companion'; index: number }
  /** Which values-index is the WIDE orbit (the $064 cluster) — drives the spin
   *  badge's ring size. */
  orbitWideIndex?: number
  /** Tooltip: what the variant changes (the "nudge to flip" coaching is
   *  appended generically by the renderer). */
  hint: string
}

const DIR = 'Direction'

export const SPRITE_PARITY_VARIANTS: Record<number, SpriteParityVariant[]> = {
  // ── Shared 'Direction' category (purely left/right, up/down, or mirror) ──
  0x089: [{ axis: 'y', label: DIR, values: ['Sweeps right first', 'Sweeps left first'], dirs: ['right', 'left'], hint: 'Horizontal platform: initial sweep direction comes from the Y cell parity (the perpendicular axis, so sliding it along its track never flips it).' }],
  0x08a: [{ axis: 'x', label: DIR, values: ['Sweeps down first', 'Sweeps up first'], dirs: ['down', 'up'], hint: 'Vertical platform: initial sweep direction comes from the X cell parity.' }],
  0x0ea: [{ axis: 'x', label: DIR, values: ['Falls first', 'Rises first'], dirs: ['down', 'up'], hint: 'Bob phase around the spawn height.' }],
  0x0eb: [{ axis: 'x', label: DIR, values: ['Drifts right first', 'Drifts left first'], dirs: ['right', 'left'], hint: 'Drift phase around the spawn column.' }],
  0x103: [{ axis: 'x', label: DIR, values: ['Toss arc normal', 'Toss arc mirrored'], hint: 'The boo-guy toss animation is horizontally mirrored on odd columns.' }],
  0x104: [{ axis: 'x', label: DIR, values: ['Jumps right', 'Jumps left'], dirs: ['right', 'left'], hint: 'Leap direction (patrols around the spawn point).' }],
  0x12f: [{ axis: 'x', label: DIR, values: ['Starts left end, moves right', 'Starts right end, moves left'], dirs: ['right', 'left'], hint: 'Patrols ±3 cells around the placement.' }],
  0x130: [{ axis: 'x', label: DIR, values: ['Starts top end, moves down', 'Starts bottom end, moves up'], dirs: ['down', 'up'], hint: 'Patrols ±3 cells around the placement.' }],
  0x13e: [{ axis: 'x', label: DIR, values: ['Starts rising', 'Starts falling'], dirs: ['up', 'down'], hint: 'Bob phase around the spawn height.' }],
  0x13f: [{ axis: 'x', label: DIR, values: ['Heads right', 'Heads left'], dirs: ['right', 'left'], hint: 'Starts a hop to the side and swims/faces this way.' }],
  0x140: [{ axis: 'x', label: DIR, values: ['Faces right', 'Faces left'], dirs: ['right', 'left'], hint: 'Facing during its vertical jumps.' }],
  // $144 flipper: X cell parity rotates the paddle pair to send Yoshi left vs right (asm: $144
  // Init reads $70E2&$10 → $7A36 = ±$80 → a 90° orientation). NOT a spinner (it used to be in the
  // auto-spin cw/ccw family — corrected). The canvas renders the rotated pair via the custom offramp.
  0x144: [{ axis: 'x', label: DIR, values: ['One-way right', 'One-way left'], dirs: ['right', 'left'], hint: 'One-way flipper orientation from the X cell parity (even = right, odd = left; asm $7A36 ±$80 → a 90° rotation).' }],
  0x152: [{ axis: 'x', label: DIR, values: ['Starts descending', 'Starts ascending'], dirs: ['down', 'up'], hint: 'Bob phase around the spawn height.' }],
  0x165: [{ axis: 'x', label: DIR, values: ['Bounces away right', 'Bounces away left'], dirs: ['right', 'left'], hint: 'Sideways drift while it bounces; the Nipper Plant it germinates into faces the same way.' }],
  0x16e: [{ axis: 'x', label: DIR, values: ['Heads right first', 'Heads left first'], dirs: ['right', 'left'], hint: 'Bob direction around the spawn column.' }],
  0x16f: [{ axis: 'x', label: DIR, values: ['Heads down first', 'Heads up first'], dirs: ['down', 'up'], hint: 'Bob direction around the spawn height.' }],
  0x182: [{ axis: 'x', label: DIR, values: ['Sets off right', 'Sets off left'], dirs: ['right', 'left'], hint: 'Initial facing of its figure-eight drift around the spawn point.' }],
  0x183: [{ axis: 'x', label: DIR, values: ['Starts right of spawn, drifting left', 'Starts left of spawn, drifting right'], dirs: ['left', 'right'], hint: 'Spawn-side offset (±32px) + initial drift of its lazy loop around the spawn point.' }],
  0x197: [{ axis: 'xy', label: DIR, values: ['Up', 'Right', 'Left', 'Down'], hint: 'Which way the sign points (the canvas renders the resolved rotation). In-game the sign also re-centres itself in its 32px block, so all four placements of a 2×2 cell group display at the same spot.' }],
  0x198: [{ axis: 'xy', label: DIR, values: ['Up-left', 'Up-right', 'Down-left', 'Down-right'], hint: 'Which diagonal the sign points (the canvas renders the resolved rotation). In-game the sign also re-centres itself in its 32px block.' }],

  // ── Behavioural variants ─────────────────────────────────────────────────
  0x017: [{ axis: 'x', label: 'Hop range', values: ['Wanders a few tiles', 'Hops in place'], hint: 'Patrol leash on net hop displacement (not hop length).' }],
  0x01c: [{ axis: 'xy', label: 'Destroy reward', values: ['Nothing', 'Star shower (up to 6, +10 each)', '1-UP', 'Tackling Bumpty ambush'], hint: 'What destroying the snowman yields. The Bumpty variant also self-triggers when Yoshi comes close.' }],
  0x030: [{ axis: 'x', label: 'Variant', values: ['Plain walker', 'Carries a stolen Green Egg'], hint: 'The egg-stealer variant spawns holding a Green Egg.' }],
  0x031: [{ axis: 'x', label: 'Variant', values: ['In a pot', 'Bare walker'], hint: 'The potted variant spawns a Small Pot around it.' }],
  0x032: [{ axis: 'x', label: 'Variant', values: ['Peeks from nest forever', 'Emerges and attacks'], hint: 'Peek-animation loop vs the 5-step emerge/hop/lunge sequence.' }],
  0x033: [{ axis: 'x', label: 'Variant', values: ['Visible immediately', 'Hidden, emerges later'], hint: 'The hidden variant starts invisible and pops out of the nest later.' }],
  0x045: [{ axis: 'xy', label: 'Boss staging', values: ['Boss fight', 'Replaced by Frog Pirate', 'Boss fight', 'Swallow-intro cinematic'], hint: 'Prince Froggy init staging: even X = the real boss; odd X picks Frog Pirate replacement or the swallow cinematic by Y parity.' }],
  0x048: [{ axis: 'x', label: 'Boss intro', values: ['×-4 castle set', '×-8 castle set'], hint: 'Per-world spell colours + which boss-battle music the fight uses (the ×-4 vs ×-8 entry of the 2-per-world tables).' }],
  0x052: [{ axis: 'x', label: 'Spawning', values: ['Single balloon', 'Continuous generator'], badge: { kind: 'generator', index: 1 }, hint: 'Odd column arms the balloon generator flag.' }],
  0x05f: [{ axis: 'x', label: 'Rotate pause', values: ['Pauses 96 frames', 'Pauses 128 frames'], hint: 'Dwell between auto-rotations — boards on opposite parities tilt out of phase with each other.' }],
  0x067: [{ axis: 'xy', label: 'Prize', values: ['5 stars', '6-leaf sunflower', 'Flower', 'Bubbled 1-UP'], hint: 'What the cloud yields once revealed (by Chomp Rock / snowball) and popped. The sunflower variant skips the item-memory collected check. No corner badge — the editor draws the prize as a full-tile icon above the cloud when selected (sprite-prizes.ts).' }],
  0x076: [{ axis: 'x', label: 'Detach arc', values: ['Flies up-left or down-right', 'Flies down-left or up-right'], hint: 'Which diagonal pair the launch velocity uses when it lets go of its chain (which half of the pair depends on swing phase).' }],
  0x077: [{ axis: 'x', label: 'Detach arc', values: ['Flies up-left or down-right', 'Flies down-left or up-right'], hint: 'Which diagonal pair the launch velocity uses when it lets go of its chain (which half of the pair depends on swing phase).' }],
  0x071: [{ axis: 'xy', label: 'Form', values: ['Big Boo w/ 3 Boos', 'Big Boo', 'Big Boo w/ 3 Boos', 'Boo'], hint: 'Cell parity picks the figure (init_big_boo reads position bits 4): an even column spawns the Big Boo escorted by 3 small Boos (and it chases Yoshi); an odd column spawns a lone drifter — a full-size Big Boo on even rows, a single small Boo on odd rows.' }],
  0x08b: [{ axis: 'x', label: 'Variant', values: ['Standard', 'Pre-inflated (alt palette)'], hint: 'Odd column starts in the inflated phase with the alternate palette.' }],
  0x08d: [{ axis: 'xy', label: 'Carries', values: ['Star shower (up to 5)', 'Red coin', '1-UP', '1-UP'], hint: 'What the Fly Guy drops when popped.' }],
  0x090: [{ axis: 'x', label: 'Reach', values: ['Short reach (66 px)', 'Long reach (98 px)'], hint: 'How far down it can stretch when lunging for Baby Mario.' }],
  0x09f: [{ axis: 'x', label: 'Spit pattern', values: ['Single spit per cycle', 'Three-spit volley'], hint: 'How many Needlenoses each lift-and-spit cycle lobs before the ball drops back.' }],
  0x0af: [{ axis: 'xy', label: 'Variant', values: ['Normal bubble', 'Normal bubble', 'Hidden bubble', 'Drifting bubble'], hint: 'Odd row enables the special forms: hidden (even column) or drifting (odd column).' }],
  0x0b0: [{ axis: 'xy', label: 'Variant', values: ['Normal bubble', 'Normal bubble', 'Hidden bubble', 'Drifting bubble'], hint: 'Odd row enables the special forms: hidden (even column) or drifting (odd column).' }],
  0x0b1: [{ axis: 'xy', label: 'Variant', values: ['Normal bubble', 'Normal bubble', 'Hidden bubble', 'Drifting bubble'], hint: 'Odd row enables the special forms: hidden (even column) or drifting (odd column).' }],
  0x0b2: [{ axis: 'xy', label: 'Variant', values: ['Normal bubble', 'Normal bubble', 'Hidden bubble', 'Drifting bubble'], hint: 'Odd row enables the special forms: hidden (even column) or drifting (odd column).' }],
  0x0b3: [{ axis: 'xy', label: 'Variant', values: ['Normal bubble', 'Normal bubble', 'Hidden bubble', 'Drifting bubble'], hint: 'Odd row enables the special forms: hidden (even column) or drifting (odd column).' }],
  0x0b4: [{ axis: 'xy', label: 'Variant', values: ['Normal bubble', 'Normal bubble', 'Hidden bubble', 'Drifting bubble'], hint: 'Odd row enables the special forms: hidden (even column) or drifting (odd column).' }],
  0x0b5: [{ axis: 'xy', label: 'Prize', values: ['1-UP', '5 stars', 'Red switch', '5 stars'], hint: 'What the hidden cloud yields on pop. The editor renders the parity-revealed winged-cloud sprite ($0BE/$0C1/$0CC) at 50% opacity, plus a full-tile prize icon above the cloud when selected (sprite-prizes.ts).' }],
  0x0be: [{ axis: 'x', label: 'Variant', values: ['Stationary', 'Moving'], hint: 'The moving variant drifts horizontally.' }],
  0x0df: [{ axis: 'x', label: 'Variant', values: ['Blue — fixed-direction leaps', 'Gold — homes on Yoshi'], hint: 'Blue repeats leaps in its spawn direction; gold re-aims at Yoshi every leap.' }],
  0x0e0: [{ axis: 'x', label: 'Climb steps', values: ['2 stair-steps per cycle', '5 stair-steps per cycle'], hint: 'How many rises per swim wave.' }],
  0x0e2: [{ axis: 'x', label: 'Mount', values: ['Floor', 'Ceiling'], hint: 'Ceiling-mounted Boo Blahs hang upside-down.' }],
  0x0e3: [{ axis: 'x', label: 'Mount', values: ['Floor', 'Ceiling'], hint: 'Ceiling-mounted Boo Blahs hang upside-down.' }],
  0x0e6: [{ axis: 'y', label: 'Spawning', values: ['Single Gusty', 'Continuous generator'], badge: { kind: 'generator', index: 1 }, hint: 'Odd row turns this into a Gusty generator (matches the cyan badge).' }],
  0x0e7: [{ axis: 'x', label: 'Spawning', values: ['Spawns a partner Burt', 'Lone Burt'], badge: { kind: 'companion', index: 0 }, hint: 'Even column spawns the classic Burt pair.' }],
  0x0e8: [{ axis: 'xy', label: 'Variant', values: ['Normal Goonie', 'Normal Goonie', 'Flock respawner (left edge)', 'Flock respawner (right edge)'], hint: 'Odd row makes it an invisible flock-edge respawner; column picks the screen edge.' }],
  0x0f4: [{ axis: 'x', label: 'Spits', values: ['Green Eggs', 'Bouncing Needlenoses'], hint: 'Which projectile the Egg-Plant produces.' }],
  0x11b: [{ axis: 'x', label: 'Spawning', values: ['Single Lakitu', 'Spawns a second Lakitu'], badge: { kind: 'companion', index: 1 }, hint: 'Odd column spawns a pair (matches the cyan badge).' }],
  0x125: [{ axis: 'x', label: 'Variant', values: ['Ending-cinematic Kamek', 'Mid-level chasing Kamek'], hint: 'Which Kamek behaviour script runs.' }],
  0x12b: [{ axis: 'x', label: 'Variant', values: ['Red — slow walker', 'Green — fast walker'], hint: 'Walk speed + palette + animation set.' }],
  0x12c: [{ axis: 'x', label: 'Variant', values: ['Fly Guy (hovering patrol)', 'Whirly Guy (flees upward, flashing)'], hint: 'Hovering carrier vs the palette-cycling flee-upward form.' }],
  0x145: [{ axis: 'x', label: 'Drop trigger', values: ['Yoshi within 96 px', 'Yoshi within 48 px'], hint: 'Horizontal detection radius for the stretch-and-drop attack.' }],
  0x146: [{ axis: 'x', label: 'Drop trigger', values: ['Yoshi within 96 px', 'Yoshi within 48 px'], hint: 'Horizontal detection radius for the stretch-and-drop attack.' }],
  0x153: [{ axis: 'xy', label: 'Variant', values: ['Normal Goonie', 'Normal Goonie', 'Flock respawner (left edge)', 'Flock respawner (right edge)'], hint: 'Odd row makes it an invisible flock-edge respawner; column picks the screen edge.' }],
  0x156: [{ axis: 'x', label: 'Persistence', values: ['Despawns normally', 'Returns to its spawn point'], hint: 'Odd columns arm a respawn anchor: when the jack would despawn off-screen (it hops away chasing Yoshi), it instantly snaps back to its spawn point instead. Confirmed by Mesen trace (both init paths) 2026-06-11.' }],
  0x157: [{ axis: 'x', label: 'Variant', values: ['Hides in wall, peeks out to throw', 'Always out, throwing'], hint: 'In-wall peek cycle vs the permanently-exposed thrower.' }],
  0x161: [{ axis: 'xy', label: 'Reward', values: ['Coin', 'Key', 'Flower', 'Door'], hint: 'What appears once every enemy in the room is defeated (item-memory guarded). The reward icon draws full-tile above the sprite when selected (sprite-prizes.ts).' }],
  0x166: [{ axis: 'x', label: 'Spawning', values: ['Single Thunder Lakitu', 'Spawns a second'], badge: { kind: 'companion', index: 1 }, hint: 'Odd column spawns a pair (matches the cyan badge).' }],
  0x170: [{ axis: 'x', label: 'Variant', values: ['Drifts horizontally', 'Stationary pop-up'], hint: 'Drifting patrol vs surfacing in place.' }],
  0x19c: [{ axis: 'x', label: 'Variant', values: ['Hovers around its perch', 'Swoops off immediately'], hint: 'Hover mode bobs around the spawn point before diving; the swoop variant starts moving straight away.' }],
  0x1a7: [{ axis: 'y', label: 'Throws', values: ['Bombs (Short Fuse)', 'Needlenoses (Seedy Sally)'], hint: 'Which projectile this grinder lobs from the trees.' }],
  0x1ab: [{ axis: 'x', label: 'Pops into', values: ['Coin', 'Red POW switch'], hint: 'What the balloon releases when popped.' }],

  // ── Colour (visual-only — spawn-cell X+Y parity picks an OBJ palette row) ──
  // The shy-guy family: pixel bit 4 of X and Y (the 16px cell LSBs) index a 4-entry
  // palette table → rows 0/1/2/4 = green/red/yellow/pink (Bank04 DATA_shy_guy_palette_indices
  // and the per-variant equivalents). The engine renders this via SPRITE_PARITY_PALETTE;
  // these rows surface it in the panel so a user knows colour follows placement.
  0x01e: [{ axis: 'xy', label: 'Colour', values: ['Green', 'Red', 'Yellow', 'Pink'], hint: 'Shy Guy colour comes from the spawn cell’s X+Y parity (OBJ palette rows 0/1/2/4). Nudge it one column/row to recolour it.' }],
  0x0f2: [{ axis: 'xy', label: 'Colour', values: ['Green', 'Red', 'Yellow', 'Pink'], hint: 'Stilt Guy colour comes from the spawn cell’s X+Y parity (OBJ palette rows 0/1/2/4).' }],
  0x0f3: [{ axis: 'xy', label: 'Colour', values: ['Green', 'Red', 'Yellow', 'Pink'], hint: 'Woozy Guy colour comes from the spawn cell’s X+Y parity (OBJ palette rows 0/1/2/4).' }],
  0x124: [{ axis: 'xy', label: 'Colour', values: ['Green', 'Red', 'Yellow', 'Pink'], hint: 'Stretch colour comes from the spawn cell’s X+Y parity (OBJ palette rows 0/1/2/4).' }],
  0x192: [{ axis: 'xy', label: 'Colour', values: ['Green', 'Red', 'Yellow', 'Pink'], hint: 'Petal/Mufti Guy colour comes from the spawn cell’s X+Y parity (OBJ palette rows 0/1/2/4).' }],
  // $133 shares the shy-guy palette MACHINE (rows 0/1/2/4 by X+Y parity) but loads the lantern-ghost
  // spriteset palette, so those rows render orange/green/grey/brown (NOT the Shy Guy's
  // green/red/yellow/pink). Order is parity-index [0,1,2,4] = row colours, capture-confirmed.
  0x133: [{ axis: 'xy', label: 'Colour', values: ['Orange', 'Green', 'Grey', 'Brown'], hint: 'Lantern Ghost body colour comes from the spawn cell’s X+Y parity (OBJ palette rows 0/1/2/4) — same machine as the Shy Guy, but its spriteset palette renders those rows orange/green/grey/brown. The held lantern flame keeps its own colour.' }],

  // $064 also picks its orbit radius from Y parity (its spin direction from X
  // parity is the calibrated Spin row in sprite-variant-hints.ts). EVEN row =
  // wide: the Main's read (`LDA $7182,x : AND #$0010`, Bank04.asm:8426) runs
  // AFTER the shared init's `SBC #$0008` Y-centering, whose borrow flips bit 4
  // — so the resolved variant is the INVERSE of the raw placement parity
  // (in-game verified 2026-06-11).
  0x064: [{ axis: 'y', label: 'Orbit', values: ['Wide orbit', 'Tight orbit'], orbitWideIndex: 0, hint: 'Cluster orbit radius (matches the spin badge ring size).' }]
}

// Graphic/Palette Changers $1BA-$1C9: WHICH header field the changer swaps is
// its column parity (even = BG1 tileset, odd = BG1 palette — the static
// equivalent of `CODE_init_palette_spr`'s `LDA $7960 : LSR : BCS` branch; see
// engine/bg1-regions.ts, verified byte-exact against a live VRAM dump). The
// target VALUE is the sprite id itself (num - $1BA) — editable via the
// Properties panel's "Changer value" field (property-schema.ts).
for (let num = 0x1ba; num <= 0x1c9; num++) {
  SPRITE_PARITY_VARIANTS[num] = [{
    axis: 'x',
    label: 'Changes',
    values: ['BG1 tileset', 'BG1 palette'],
    hint: `Which BG1 header field this changer swaps to 0x${(num - 0x1ba).toString(16).toUpperCase()} from its column onward.`
  }]
}

/** Resolved arrow direction for a Direction-category parity sprite (drives
 *  the on-outline arrow badge), or null for sprites without one (behavioural
 *  variants, the mirror-only mace, non-parity sprites). */
export function parityDirection(num: number, x: number, y: number): ParityDirection | null {
  const variants = SPRITE_PARITY_VARIANTS[num]
  if (!variants) return null
  for (const v of variants) {
    if (!v.dirs || v.axis === 'xy') continue
    return v.dirs[resolvedIndex(v, x, y)]
  }
  return null
}

/** Internal: resolve a variant's values-index for a placement. */
function resolvedIndex(v: SpriteParityVariant, x: number, y: number): number {
  return v.axis === 'xy' ? 2 * (y & 1) + (x & 1) : (v.axis === 'x' ? x : y) & 1
}

/** Active spawn-variant badge for a placement ('generator' = continuous
 *  emitter, 'companion' = one-shot extra spawn), or null when the sprite has
 *  no spawn variant or sits at the inactive parity. */
export function paritySpawnBadge(num: number, x: number, y: number): 'generator' | 'companion' | null {
  for (const v of SPRITE_PARITY_VARIANTS[num] ?? []) {
    if (v.badge && resolvedIndex(v, x, y) === v.badge.index) return v.badge.kind
  }
  return null
}

/** Whether an orbit-variant placement resolves to the WIDE orbit; null for
 *  sprites without an orbit variant (their ring size is fixed). */
export function parityOrbitWide(num: number, x: number, y: number): boolean | null {
  for (const v of SPRITE_PARITY_VARIANTS[num] ?? []) {
    if (v.orbitWideIndex !== undefined) return resolvedIndex(v, x, y) === v.orbitWideIndex
  }
  return null
}

export interface ParityVariantRow {
  label: string
  value: string
  hint: string
}

/** Resolved variant rows for a placed sprite (empty for sprites without
 *  parity variants). The hint gets the generic "how to change it" coaching
 *  appended so every row teaches the mechanism. */
export function parityVariantRows(num: number, x: number, y: number): ParityVariantRow[] {
  const variants = SPRITE_PARITY_VARIANTS[num]
  if (!variants) return []
  return variants.map((v) => {
    const idx = resolvedIndex(v, x, y)
    const nudge =
      v.axis === 'xy'
        ? 'Derived from the X+Y cell parity — nudge one column/row to change it.'
        : v.axis === 'x'
          ? 'Derived from the X cell parity — nudge one column to flip it.'
          : 'Derived from the Y cell parity — nudge one row to flip it.'
    return { label: v.label, value: v.values[idx], hint: `${v.hint} ${nudge}` }
  })
}
