;#############################################################################################################
;# AmbientSpriteIDs.asm -- Ambient sprite IDs (the 16-slot table).
;#
;# See also (sibling reference files):
;#   ys_enmy.asm + ys_enmy2.asm..ys_enmy14.asm -- per-sprite generator/handler bodies (most
;#                                                generators in the $1CA..$1F4 range have
;#                                                handlers distributed across this family)
;#   ys_chr.asm                                 -- ambient-sprite spawn / character glue
;#                                                (auto-scroll setters interact with player code)
;#
;# Sprite ID space:
;#   $000-$1A9   Normal enemies, platforms, items, interactives (see NormalSpriteIDs.asm)
;#   $1AA-$1B9   Boss-related (doors, explosion, defeated key)
;#   $1BA-$1C9   Auto-scroll controllers, graphics/palette swap triggers
;#   $1CA-$1F4   Sprite generators (Gusties, Fangs, Flutters, Baron von Zeppelin, etc.)
;#   $1F5-$22E   V1.1 framework extensions (additional generators / markers / unused)
;#   $22F-$244   Sparse, marked Invalid; intro-cutscene-only / engine-reserved
;#
;# Ambient sprites occupy the lower 16-slot table at WRAM $70:0EC0..0EFF: 16 slots interleaved
;# with the 24 regular-sprite slots at $70:0F00.. Each slot is 4 bytes per field; the ID stored
;# in $70:1320..135F is the value defined here.
;#
;# Functional groupings within the ambient range (corrected from runtime
;# spawn-site tracing -- earlier positional-inference labels conflated adjacent IDs into
;# fictitious "generator start/end" pairs; in reality most of the $1E0..$22E range is
;# made up of shared particle/VFX slots that many unrelated sprite families spawn through
;# generic engine helpers like CODE_03B56B (stomp puff) / CODE_009519 / CODE_009548 /
;# CODE_009531 (placeholder timers with different stride). Where a slot really is shared
;# across many sprites, it's noted "(universal)".):
;#   $1BA..$1C9   water splash + bubble + eggshell + small bopping + score popup +
;#                multi-stage puffs (water/swim engine consumes several; many GSU-only)
;#   $1CA..$1D6   multi-stage puff/burst slots used by per-sprite handlers
;#                ($1CD = generic medium puff with 10+ callers; $1DF likewise)
;#   $1D4..$1DE   originally labeled "auto-scroll setters" -- actually a mixed pool of
;#                enemy/object attack puffs ($1D4 = clawdaddy/ghost/balloon-pop puff,
;#                $1D5 = bullet-bill cannon smoke, $1D8 = HarryHedgehog dust trail,
;#                $1DD = boss-arena sparkle, etc.). NOT auto-scroll setters.
;#   $1DF         universal damage/contact puff (10+ callers)
;#   $1E1/$1E2    whirlwind / BlowHard wind-burst pair
;#   $1E3         dormant placeholder timer (no observed spawn)
;#   $1E4         coin / red-coin / 1-up pickup sparkle (universal pickup VFX)
;#   $1E5         dormant placeholder timer (no observed spawn)
;#   $1E6         enemy stomp impact puff (universal, 14 inline-copy spawn sites; the CODE_03B56B helper is itself one of the 14, not a JSL hub)
;#   $1E7         enemy stomp puff variant (CODE_03B56E)
;#   $1E8         EggoDilFace petal-launch puff
;#   $1E9         BlowHard SuperFX-rendered burst
;#   $1EA/$1EB    SpearGuy spear-throw paired sparkle (start/twin)
;#   $1EC         Cannonball / Bomb mid-flight trail particle
;#   $1ED         Cannonball / Bomb explosion puff
;#   $1EE         shared vanish puff (Sluggy stomp, Milde gulp, balloon-pop, Burt)
;#   $1EF         Baron Von Zeppelin carry-cargo trail particle (9 sites in Bank07; also reused as fade-out puff by HealthStar Main + HoppingSilverTapTap Main)
;#   $1F0         IcyWatermelon freeze-shard helper
;#   $1F1         BabyBowser fight area puff
;#   $1F2         break-frozen-enemy puff (via CODE_03B595, 6 callers)
;#   $1F3         crate-break shrapnel ($003 / $10E)
;#   $1F4         Georgette Jelly drip puff
;#   $1F5         Snifit projectile smoke
;#   $1F6         Snifit / GreenGlove attack puff
;#   $1F7         ShyguyOnStilts wobble puff
;#   $1F8         Lakitu cloud-trail particle (regular / Aqua / Thunder variants)
;#   $1F9         GreenGlove ambient projectile particle
;#   $1FA         HorizontalLavaDrop trail puff
;#   $1FB         VerticalLavaDrop trail puff
;#   $1FC         DanglingFang descent / attack puff
;#   $1FD         FlopsyFish jump-splash
;#   $1FE         FlopsyFish jump-arc anticipation flash
;#   $1FF         Goonie patrol companion
;#   $200         RotatingArrowCloud charge-up sparkle
;#   $201         AquaLakitu fishing-rod splash
;#   $202/$203    Flutter spore particles (paired)
;#   $204..$206   SprayFish water-spray (3 stage variants)
;#   $207         Grunt walking-dust trail
;#   $208         universal enemy death-pop OAM (via CODE_03B4D6, 6+ callers)
;#   $209         BlowHard wind sparkle
;#   $20A         ZeusGuyBlast lightning-impact mirror-flash
;#   $20B         ChompRock smash debris
;#   $20C         Hookbill-arena + ChompRock destruction debris
;#   $20D/$20E    ThunderLakitu lightning-bolt sparkle (paired)
;#   $20F         ThunderLakituFireball impact-blink
;#   $210         Mufti-Guy flower-disguise petal burst
;#   $211         Goonie attack-burst petals
;#   $212         Crazee Dayzee "happy notes" emote
;#   $213         WatermelonFlame smoke trail (fire-watermelon)
;#   $214         GSU-only burst (no SNES-side spawn)
;#   $215         Skeleton Goonie patrol companion
;#   $216         Skeleton Goonie wing-loss puff
;#   $217         Salvo the Slime droplet ground-bounce
;#   $218         BowserFightGiantEgg debris (final boss fight)
;#   $219         Little Skull Mouser appearance/disappearance puff
;#   $21A         KeyholeCork pop-out puff
;#   $21B/$21E    HotLips fire-blast smoke (paired)
;#   $21C/$21D    GSU-only timed particles
;#   $21F         Raphael the Raven death twinkle
;#   $220         Kamek (cutscene) magic-spell sparkle
;#   $221         Prince Froggy StomachAcid drip splash
;#   $222         Naval Piranha defeat-debris dirt chunk
;#   $223         Hookbill dead-pancake squish particles
;#   $224         pipe-warp sparkle (horizontal pipe entrance)
;#   $225         dormant placeholder timer (no observed spawn)
;#   $226         coin-pickup spinning-coin popup
;#   $227         BowserRoomKamek magic-spell launch sparkle
;#   $228         ZeusGuy lightning-spark particle
;#   $229         watermelon-seed projectile trail dust
;#   $22A         CoinCannon firing-blast cone (bonus game)
;#   $22B/$22D    Bandit-minigame JACKPOT chain (jackpot row head -> jackpot popup tail)
;#   $22C/$22E    Bandit-minigame regular-row chain (non-jackpot row head -> final fade)
;#                Bank11 also spawns $22B/$22C/$22E directly from minigame code paths,
;#                so the head -> tail link is not strictly linear.
;# The four `_Invalid` slots at the bottom of this file are confirmed (asm-side) to be
;# unallocated in the V1.0/V1.1 cart we build against.
;#
;# Variant mechanism -- relevant for normal sprites, not ambient ones:
;# certain sprites (e.g. the ?-cloud family) use the LSBs of X/Y tile position bytes as variant
;# selectors. Ambient sprites in the auto-scroll/generator range generally do NOT use this
;# mechanism; their position bytes are pure position (or unused, for auto-scroll setters).
;#############################################################################################################

!Define_YI_AmbSpr1BA = $01BA	; (auto-scroll/swap-trigger band start) | Water splash for transition (player entering/leaving water): handler CODE_ambient_water_splash_transition (=CODE_008CBF) walks 13-entry stride-2 OAM splash sequence (DATA_008C8B tiles / DATA_008CA5 holds), then auto-despawns on lifetime expiry. Spawn: Player water enter/exit (Bank02:14419 in Naval Piranha bud emerge area; Bank06:13334 SewerGhostWithPlatform_Main; Bank07 multiple swimming/water sites; Bank0C:7581 BabyMario/water; SuperFX Bank0A:4644 + Bank0B:9735 water splash dispatch).
!Define_YI_AmbSpr1BB = $01BB	; (auto-scroll/swap-trigger band) | Water splash from swimming player: per-frame Y-position nudge via DATA_008CE0 offset table giving a small vertical bob effect, freeze-aware. Spawn: SuperFX Bank0B:9787 (GSU swim/water dispatch; no SNES-side LDA spawn site found -- spawned exclusively by the GSU water-effect engine).
!Define_YI_AmbSpr1BC = $01BC	; (auto-scroll/swap-trigger band) | Underwater bubble: rises with periodic Y-decrement and small X-jitter from DATA_008D17; uses RNG bit; despawns when bubble flag $7822 hits zero. Spawn: SuperFX Bank0A:4596 + Bank0B:9835 (GSU water/swim engine; no SNES-side spawn site -- GSU-only).
!Define_YI_AmbSpr1BD = $01BD	; (auto-scroll/swap-trigger band) | Eggshell fragment: one-shot single-frame setup that ORs $0080 into $7002 (priority/flip flags) and otherwise idles; despawn handled by lifetime expiry. Spawn: CODE_04F88E shared helper that loops X=$06,$04,$02,$00 to fire 4 shell fragments around a center; callers are Mock-Up Laid Egg pop ($087 in Bank0F:2361), egg-throw breakage (Bank03:7081), goal-award flashing-egg burst (Bank02:4579), and the goal-award setup path (Bank04:14486). See docs/family-eggs.md.
!Define_YI_AmbSpr1BE = $01BE	; (auto-scroll/swap-trigger band) | Small bopping animation: increments OAM tile index ($73C2) every frame, freeze-aware; trivial 1-instruction "advance frame" handler for tiny effects. Spawn: head-bop / egg-hit sparkle via CODE_spr_state_on_head_bop (Bank03:4454) + the CODE_03A0E7 player-egg-hit shell-bounce helper (Bank03:4489) + an egg-handler hit-flash branch (Bank03:8704).
!Define_YI_AmbSpr1BF = $01BF	; (auto-scroll/swap-trigger band) | Score sprites: no per-frame logic beyond the standard freeze check; OAM-only display whose lifetime decrement causes auto-despawn (used by score numerals). Spawn: CODE_spawn_1up_score / CODE_spawn_3up_score helpers at Bank03:5060/5055 (single spawn site at Bank03:5080 -- all callers funnel through here); used by 1up cards, Bandit prize-cards, Bonus-game results.
!Define_YI_AmbSpr1C0 = $01C0	; (auto-scroll/swap-trigger band) | Multi-stage frame animation (5-step): handler CODE_008DB2 walks DATA_008DA9 (5 tile entries $02,$01,$00,$FF,$00) + DATA_008DAE (4 holds $06,$06,$06,$03) driving OAM tile $73C2 and palette-attr $7000 (the $73C2=$FF stage clears $7000 low 2 bits); sets per-stage hold $7782. One of the kicked-up dust / contact spark variants. Spawn: $02D Salvo the Slime defeat-shrink puff (Bank06:1664 in Salvo_Main); $0D7 Sluggy defeat-shrink puff (Bank02:9817 sluggy_defeat_shrink); also referenced as a Burt-the-Bashful death-puff via SuperFX command-buffer at Bank06:4390 ($6000=$01C0).
!Define_YI_AmbSpr1C1 = $01C1	; (auto-scroll/swap-trigger band) | Direction/state-from-timer effect: handler CODE_008DE7 maps lifetime byte $7782 (LSR x3) onto OAM tile $73C2 each frame -- a smooth 8-bucket fade/morph driven purely by timer. Spawn: (no runtime spawn site found -- handler is dormant in the AmbSpr dispatch table; not present in the Burt-the-Bashful GSU command-buffer at Bank06:4390+).
!Define_YI_AmbSpr1C2 = $01C2	; Player transformation flash sparkle: handler CODE_008DF8 decrements $7782 each frame (accelerated double-dec once lifetime < $3F), then writes ($7782 LSR 1 AND #$07) into $73C2 -- 8-bucket cycle that speeds up at the end of the lifetime; despawns when lifetime hits zero. Renders the transform-flash arc around Yoshi. Spawn: player-state $10 transforming (helicopter/sub/train morph) -- Bank04:13500 inside CODE_player_state_10_transforming; also a Burt-the-Bashful GSU command-buffer entry at Bank06:4392 ($6002=$01C2).
!Define_YI_AmbSpr1C3 = $01C3	; (auto-scroll/swap-trigger band; referenced from Bank0E:1436) | 2-frame stutter blink: lifetime drives $73C2 with a forced 2-frame hold each step; despawns on $73C2 underflow (basic blink-then-die). Spawn: $0FD ZeusGuy lightning impact (Bank07:10937 + 11655 ZeusGuy_Main); $0A6/$0A8 IncomingChomp dust (Bank0E:1453); generic stone/ground-stamp via CODE_change_map16 follow-up at Bank0C:441 + 7518 (level-load tile-stamp puffs) + Bank0D:4752 (Bigger Boo defeat).
!Define_YI_AmbSpr1C4 = $01C4	; (graphics/palette-swap band) | 3-stage animation via DATA_008E34 (3 tile entries $02,$01,$00) + DATA_008E30 (4 hold entries $09,$07,$06,$03); handler CODE_008E37 indexes by $7E4C-1, decrements stage on hold expiry; small kicked-up sparkle/puff variant. Spawn: $015 SubmarineTorpedo trail puff (Bank04:310 in SubmarineTorpedo_Main); also a Burt-the-Bashful GSU command-buffer entry (Bank06:4398, $6008=$01C4) and a GSU IWT path (SuperFX Bank0B:3339).
!Define_YI_AmbSpr1C5 = $01C5	; (palette-swap) | 6-stage countdown animation (DATA_008E58 hold times); decrements OAM tile $73C2 each tick down to zero; another puff/sparkle variant. Spawn: (no SNES-side LDA spawn site found) -- only GSU SuperFX IWT path (Bank0B:5650) and a Bank57 data reference; effectively GSU-only.
!Define_YI_AmbSpr1C6 = $01C6	; (palette-swap) | PPU-multiplier-driven Mode-7 rotator: handler CODE_008E7E uses sine/cosine LUTs (DATA_cosine_lut_8bit_radians / DATA_sine_lut_8bit_radians) + the SNES PPU 16-bit multiplier registers to compute X/YSpeed each tick, writes into AmbSpr velocity registers; rotates effect around an anchor. Stage table DATA_008E7A (4 holds $06,$06,$05,$05). 65816-side handler -- no GSU code involved. Spawn: (no SNES-side LDA spawn site found) -- Burt-the-Bashful GSU command-buffer entry (Bank06:4400, $600A=$01C6) + GSU IWT path (SuperFX Bank0B:6065).
!Define_YI_AmbSpr1C7 = $01C7	; (palette-swap) | 1-frame trigger by Y-velocity: if YSpeed becomes non-negative, set $73C2 = 1 (latches OAM tile change once the effect "lands"); used for a fall-landed flip. Spawn: Tap-Tap lava-death splash bubbles (Bank0F:4673 + 4728 in CODE_tap_tap_per_frame_lava_anim); generic ground-stamp puff (Bank0C:7558 level-load Map16 site); GSU IWT path SuperFX Bank0A:4678.
!Define_YI_AmbSpr1C8 = $01C8	; (palette-swap) | Lifetime LSR x3 -> OAM tile (same shape as $1C1); animation purely driven by timer, no manual stage stepping. Spawn: (no SNES-side LDA spawn site found) -- only as a Burt-the-Bashful GSU command-buffer entry (Bank06:4406); GSU-only.
!Define_YI_AmbSpr1C9 = $01C9	; (palette-swap) | Drift-with-RNG: every 8 frames pick +1 or -1 X delta from RNG and apply to subpixel-X; small horizontal jitter for floating-dust style effects. Spawn: (no runtime spawn site found -- handler is dormant in the dispatch table; only data-table references in Bank13).
!Define_YI_AmbSpr1CA = $01CA	; (palette-swap / generator boundary) | 6-stage animation (DATA_008F2F tiles, DATA_008F35 holds); stage-zero terminates the loop, otherwise standard countdown. Spawn: (no SNES-side LDA spawn site found) -- two Burt-the-Bashful GSU command-buffer entries at $601C/$601E (Bank06:4418/4419) + GSU IWT path SuperFX Bank0B:12135; GSU-only.
!Define_YI_AmbSpr1CB = $01CB	; (generator band) | 7-stage animation (DATA_008F5C tiles, DATA_008F63 holds); standard countdown-then-despawn pattern. Spawn: (no SNES-side LDA spawn site found) -- only a GSU IWT path (SuperFX Bank0B:7267); GSU-only.
!Define_YI_AmbSpr1CC = $01CC	; (generator band) | 8-stage animation (DATA_008F8B/DATA_008F93); first stage has long $40 hold so it lingers, then ticks down to zero. Spawn: $01C Dr. Freezegood ice/breath spawn (Bank05:11032); $09E ChompRock dust trail (Bank0E:9305); also Burt-the-Bashful GSU command-buffer entry (Bank06:4410).
!Define_YI_AmbSpr1CD = $01CD	; (generator band) | 11-stage animation (DATA_008FBC tiles / DATA_008FC7 holds) with grace stage that re-checks freeze; standard countdown-and-despawn used for medium-length puffs. Spawn: very widely-used generic puff helper. Single-instance sites: Bank02:4004 (CODE_02A4F4 puff-at-sprite-pos shared by door open / goal key award / KeyFromBoss state-01); Bank02:4423 (KeyFromBoss); Bank04:713 ($006 WatermelonFreeze_Main); Bank05:11697 (BulletBill_Main); Bank07:15928 (boss-area effect); Bank0C:1364 + 9895 (Bandit/level effects); Bank0E:6867 (sprite-burst); Bank0F:230 + 1172 (egg/ground-pound). The most-overloaded "medium puff" used by many sprite handlers.
!Define_YI_AmbSpr1CE = $01CE	; (generator band) | 2-stage animation (DATA_009005/DATA_009006), then despawn -- minimalist visual effect. Spawn: $02C LungeFish airborne-grab water splash (Bank04:3498 in CODE_lunge_fish_state_03_airborne_grab); also Burt-the-Bashful GSU command-buffer entry (Bank06:4412).
!Define_YI_AmbSpr1CF = $01CF	; (generator band) | Player-proximity tracker: copies regular-sprite slot Y position+8 into DP, calls CODE_049B42 (distance/lookup), latches $73C2=1 if combined offset >= $30. Used to gate visibility. Spawn: $02C LungeFish water-bubble trail (Bank04:3677 in LungeFish_Main; single spawn site).
!Define_YI_AmbSpr1D0 = $01D0	; (generator band) | 10-stage animation (DATA_009085/DATA_00908F); standard countdown-then-despawn for longer puff/burst effects. Spawn: $019 Bubble pop puff (Bank04:918 in Bubble_Main; single spawn site).
!Define_YI_AmbSpr1D1 = $01D1	; (generator band) | Freeze-only stub: only calls CODE_check_amb_sprite_freeze_no_pull and returns; OAM-rendered effect whose lifetime expiry handles despawn. Spawn: $02D Salvo the Slime body OAM placeholder spawned during SalvoTheSlime_Init (Bank06:423; single spawn site).
!Define_YI_AmbSpr1D2 = $01D2	; (generator band) | 5-stage hold-table animation (DATA_0090BE) cycling $73C2 down, then JMP despawn -- short multi-frame puff. Spawn: $132 LemonDrop fizzle puff (Bank06:2721 in LemonDrop_Main; single spawn site).
!Define_YI_AmbSpr1D3 = $01D3	; (generator band) | OAM-shrink-and-flush: per-frame shrinks the slot's 8-tile OAM cluster inward by $7E4C (shrink factor) before standard freeze+lifetime; used for vanishing/imploding effects. Spawn: $134 Baby Bowser shrink/vanish effect in BabyBowser_Main (Bank0D:10728; single spawn site).
!Define_YI_AmbSpr1D4 = $01D4	; Enemy/object attack puff (multi-source): 11-stage animation (DATA_0090E0/DATA_0090EB) with physics-driven init pull when $7E4E != 0. Spawn: $038 Potted Ghost flame helper at Bank02:113 (CODE_02808C); $070 Clawdaddy claw swipe puff (Bank05:1497 in clawdaddy_state_swipe_arc); $052 BalloonPlatform pop-puff (Bank05:7736); $120 DoubleSidedArrowLift/POW destruction puff (Bank05:15854). Notes: positional-inference labeling previously called this an "auto-scroll setter" -- corrected from runtime spawn trace.
!Define_YI_AmbSpr1D5 = $01D5	; BulletBillShooter cannon-fire smoke puff: 6-stage animation (DATA_009121 tiles, DATA_009127 holds with $08 mid-frames); standard countdown puff/burst. Spawn: $078/$079/$07A BulletBillShooter cannon-fire smoke puff (Bank05:11392 in BulletBillShooter_Main; single spawn site).
!Define_YI_AmbSpr1D6 = $01D6	; LavaBubble splash / FlamerGuy flame-emit puff: 3-stage animation (DATA_00914E tiles, DATA_009151 holds 6/4/2); short flicker effect. Spawn: $080/$081 LavaBubble splash puff (Bank05:1974 + 2155 LavaBubble_Main); $0EC/$0ED FlamerGuy flame-emit puff (Bank05:9135 FlamerGuy_Main).
!Define_YI_AmbSpr1D7 = $01D7	; Monkey watermelon-throw / Bandit kick-up dust (multi-source): handler CODE_009519 is a freeze-only no-op (JSR check_amb_sprite_freeze_no_pull / RTS) -- the slot just persists for its $7782 lifetime then auto-despawns through the shared lifetime-zero path. Generic timed-OAM "show then die" sprite, no per-frame tile movement. Spawn: $1A6 MonkeyWithWatermelon-throw + $1A9 HangingMonkeySpittingSeeds particles (Bank02:6283 grinder_main_watermelon family); $020/$0A3/$0A4 Bandit kicked-up dust (Bank0E:10760 in Bandit_Main).
!Define_YI_AmbSpr1D8 = $01D8	; HarryHedgehog rolling-dust / crate-break dust (multi-source): 3-stage animation (DATA_009175/DATA_009178) -- 3 OAM tiles with hold-time 6/4/2 then despawn. Spawn: $085 HarryHedgehog rolling-dust trail (Bank01:5404 in HarryHedgehog_Main); $003/$10E crate-break dust (Bank0D:2223 in CrateWithKey/CrateWith6Stars_Main); also Bank0D:9573 (Big-Bowser area).
!Define_YI_AmbSpr1D9 = $01D9	; FrogPirate skip-rock / splash puff: 2-stage animation (DATA_00919C/DATA_00919E) -- 2 OAM tiles with hold 12/8 then despawn. Spawn: $017 FrogPirate-related skip-rock or splash (Bank0E:13911 in FrogPirate_Main); also Bank0F:4687 (Tap-Tap lava-death adjacent).
!Define_YI_AmbSpr1DA = $01DA	; Dormant mid-air burst (no observed spawn): 3-stage animation with physics: applies acceleration via CODE_ambient_apply_physics, then walks DATA_0091C1/0091C4; injects Y-velocity #$0080 once. Spawn: (no runtime spawn site found -- handler is dormant in the dispatch table).
!Define_YI_AmbSpr1DB = $01DB	; Dormant 3-stage physics puff (no observed spawn; shared shape with $227 which reuses CODE_00921A): 3-stage animation with physics (DATA_009214 tiles 3/2/1, DATA_009217 holds 8/8/8); decrements $7E4C, despawns on stage underflow. Spawn: (no runtime spawn site found -- handler is dormant in the dispatch table).
!Define_YI_AmbSpr1DC = $01DC	; BabyBowser smash / MinigameBalloon pop puff: 11-stage animation (DATA_00923E/DATA_009249) -- mostly hold-1 frames; quick anim then despawn. Spawn: $134 BabyBowser smash/damage puff (Bank0D:9344 BabyBowser_Main); $1B6 MinigameBalloon pop puff (Bank11:3653 MinigameBalloon_Main).
!Define_YI_AmbSpr1DD = $01DD	; Boss-arena / key-glow sparkle (multi-source): 4-stage animation (DATA_009275/DATA_009279) -- uniform hold-6 frames. Spawn: $0D5 BackgroundForHookbillFight ambient sparkle (Bank02:2881); $014 KeyFromBoss-state-02 glow (Bank02:11096); $134 BabyBowser fight sparkle (Bank0D:9320); also two GSU IWT paths (SuperFX Bank0B:9121 + 9377).
!Define_YI_AmbSpr1DE = $01DE	; Dormant homing-physics tracker (no observed spawn): phase-locked physics tracker -- distance to regular sprite's position, applies DATA_0092CC tile cycle + Y-velocity nudge per stage; used by a sprite that homes toward another sprite then despawns. Spawn: (no runtime spawn site found -- handler is dormant in the dispatch table).
!Define_YI_AmbSpr1DF = $01DF	; Universal damage / contact puff (10+ callers): 5-frame countdown to $73C2 (CODE_009376 walks DATA_009371 tiles 3/2/1/0/4) -- $7E4E spawn flag selects either physics-tick (JSR CODE_008AF2) or freeze-tick (JSR CODE_check_ambient_sprite_freeze); despawn after stage underflow. The most-overloaded damage/contact puff in the game. Spawn: generic damage / impact / sparkle puff used by many sources -- $00D goal-ring handoff sparkle (Bank02:4789); $0AE Hookbill-related (Bank03:4398 + 8036); player lava-touch fountain (Bank04:12124 player_state_28_touched_lava); BurtTheBashful (Bank06:4184); various enemy/level sites (Bank07:343, Bank0C:14040, Bank0E:6482 ThunderLakituFireball_Main, Bank0F:6110, Bank10:5541).
!Define_YI_AmbSpr1E0 = $01E0	; SpearGuy spear-throw / Koopa-shell kick puff: 4-frame countdown OAM tile walk (DATA_0093A0); uniform hold-4; despawn on stage underflow. Spawn: $0FB/$0FC SpearGuy spear-throw puff (Bank07:2503 in SpearGuy_Main); $16A-$16C Koopa-shell kick puff (Bank07:12162); also Bank0D:8503 (Bigger Boo area).
!Define_YI_AmbSpr1E1 = $01E1	; Baby Mario whirlwind (Yoshi hit, baby floats away): 13-stage animation (DATA_0093C4/DATA_0093D1) with sentinel byte $FF that swaps to OAM-attribute byte instead of tile; cycles full OAM frame. Spawn: player_state_sent_towards_baby_mario (Bank04:13756 -- triggers when Yoshi gets hit and baby cries); shared whirlwind helper CODE_06BFA4 (Bank06:7172) called from BabyMario_Main + a Bank04 site.
!Define_YI_AmbSpr1E2 = $01E2	; BlowHard whirlwind-shrink pulse: OAM-shrink with SuperFX expand-pass via FXCODE_09F5F4 plot routine; SuperFX-rendered expand/shrink effect. Spawn: $0F8/$04C BlowHard whirlwind-shrink pulse (Bank0E:6371 BlowHard_Main); a whirlwind helper in Bank07:15686 (closer-cinematic boss-arena wind); also a GSU IWT path (Bank0B:13109). Notes: previous "whirlwind generator end" label was positional inference (paired with $1E1 which is the real Baby-Mario whirlwind).
!Define_YI_AmbSpr1E3 = $01E3	; Dormant placeholder slot (no observed spawn): handler CODE_009519 is a freeze-only stub (JSR CODE_check_amb_sprite_freeze_no_pull / RTS) -- no $73C2 tile-walk, no explicit despawn; lifetime is entirely driven by the spawner's $7782 init (each frame $7782 ticks via the freeze-helper fall-through to CODE_008B0D, despawning when $7782 underflows). Spawn: (no runtime spawn site found -- handler is dormant in the dispatch table). Notes: previous "Lakitu generator end" label was positional inference -- the adjacent $1E2 is actually BlowHard, not Lakitu.
!Define_YI_AmbSpr1E4 = $01E4	; Coin / red-coin / 1-up pickup sparkle (universal): CODE_009548 stride-3 timer (freeze + decrement $73C2 with hold 3) then despawn. Short fading sparkle on coin collection. Spawn: coin/red-coin pickup sparkle (Bank00:9866 in the GSU stop-code $02 handler -- "spawn ambient sprite / red coin"); $100 Bubbled1up pickup (Bank04:9205); $115 Coin pickup (Bank04:9366); goal-ring award (Bank02:4438); Bank0C:13629 + 13745 (level-load coin sites).
!Define_YI_AmbSpr1E5 = $01E5	; Dormant placeholder timer (no observed spawn): CODE_00955F stride-4 timer (freeze + decrement $73C2 with hold 4) then despawn. Spawn: (no runtime spawn site found -- handler is dormant in the dispatch table). Notes: previous "Poochy generator end" label was positional inference.
!Define_YI_AmbSpr1E6 = $01E6	; Enemy stomp impact puff (universal): handler CODE_0092AD -- 7-stage animation with $73C2 tile = stage value (TYA) and DATA_00929E hold table (uniform hold-3) then despawn; freeze-tick via shared CODE_008AF2 (no physics; physics-on-freeze variant lives at CODE_0092A5 for $1E7). The most-overloaded stomp/hit/death puff in the game. Spawn: inline copy-paste idiom at 14 sites across Bank01/02/03/04/05/06/07/0C/0E/0F -- each site reproduces the same 4-instruction sequence (LDA #!Define_YI_AmbSpr1E6 / sound $1C / JSL CODE_spawn_ambient_sprite / set $7782=4, $73C2=7, $7E4C=7). Verified caller list: Bank01:4369 (closer_salvo), Bank02:13676 ($0D5 BackgroundForHookbillFight), Bank03:4185 ($0B3 Fuzzy-Fart puff helper CODE_039F2B), Bank03:7308 (ROM $03:B56B -- the shared CODE_03B56B helper itself; one of the 14 inlines, NOT a hub: CODE_03B56B has zero JSL callers, only its fall-through entry CODE_03B56E is JSL-called by Bank03/04/05/07/0C/0E variant-ID sites for $1E7), Bank04:9645 (NumberPlatformExplosion), Bank05:7573 + 7662, Bank06:4287 (BurtTheBashful), Bank07:5189 + 13934, Bank0C:9496, Bank0E:7504 + 14721, Bank0F:6143. No Bank0D callers.
!Define_YI_AmbSpr1E7 = $01E7	; Enemy stomp puff variant (CODE_03B56E): same animation shape as $1E6 with extra physics-on-freeze branch (CODE_0092A5). Spawn: variant stomp-puff via CODE_03B56E -- $066/$054 PiranhaPlant retract puff (Bank05:4517 PiranhaPlant_Main); $11A GreenGlove pop (Bank07:4737); various enemy hit/death sites (Bank03:7693 + 10578, Bank0C:2067, Bank0E:2985 + 7242). Notes: previous "bat generator end" label was positional inference.
!Define_YI_AmbSpr1E8 = $01E8	; EggoDilFace petal-launch puff: CODE_00955F (freeze + stride-4 $73C2 countdown) -- placeholder timer; only effect is its OAM lifetime. Spawn: $0EF EggoDilFace_Main petal-launch puff (Bank05:8410; single spawn site) -- also Burt-the-Bashful GSU command-buffer entry (Bank06:4408). Notes: previous "bat-2 generator start" label was positional inference.
!Define_YI_AmbSpr1E9 = $01E9	; BlowHard SuperFX-rendered burst: handler CODE_009519 is the freeze-only stub (no $73C2 logic) -- despawn is purely $7782-lifetime-driven from the spawner; no per-frame body. Spawn: $0F8/$04C BlowHard SuperFX-rendered burst (Bank0E:5960 BlowHard_Main); also boss-closer wind cycle (Bank07:15719). Notes: previous "bat-2 generator end" label was positional inference.
!Define_YI_AmbSpr1EA = $01EA	; SpearGuy spear-throw sparkle (paired with $1EB): handler CODE_009519 is the freeze-only stub (no $73C2 logic); $7782-lifetime-driven despawn. Spawn: $0FB/$0FC SpearGuy spear-projectile spawn sparkle (Bank07:2308 SpearGuy_Main; emitted as a paired pair with $1EB below); also Burt-the-Bashful GSU command-buffer entries (Bank06:4421 + 4423).
!Define_YI_AmbSpr1EB = $01EB	; SpearGuy spear-throw sparkle twin (paired with $1EA): handler CODE_009519 is the freeze-only stub (no $73C2 logic); $7782-lifetime-driven despawn. Spawn: $0FB/$0FC SpearGuy spear-projectile twin (paired with $1EA above at Bank07:2325 SpearGuy_Main).
!Define_YI_AmbSpr1EC = $01EC	; Cannonball / Bomb mid-flight trail particle: handler CODE_009519 is the freeze-only stub (no $73C2 logic); $7782-lifetime-driven despawn -- per-frame body does nothing visible, but the slot is re-spawned at a fixed rate during cannonball flight. Spawn: $00B Cannonball / $060 Bomb mid-flight trail particles emitted every couple of frames during Cannonball-Main (Bank0E:195 -- inside the shared cannonball/bomb handler at YI_NorSpr00B_Cannonball_Main); also Burt-the-Bashful GSU command-buffer entry (Bank06:4414). See docs/family-cannons.md §6.
!Define_YI_AmbSpr1ED = $01ED	; Cannonball / Bomb explosion puff: animated via generic CODE_009548 stride-3 timer + despawn. Spawn: $060 Bomb on detonation and $00B Cannonball on impact (Bank0E:143 + Bomb-Main). Notes: previous "Bamboo Dancers dance end" label was positional inference (paired with the wrong-labeled $1EC). See docs/family-cannons.md §6.
!Define_YI_AmbSpr1EE = $01EE	; Shared vanish/dissolve puff (multi-source): 9-stage animation (DATA_00A7D1 tile holds 3/3/2/2/2/1/1/1/2) cycling $73C2 then despawn. Visible vanish puff reused by several unrelated sprite handlers. Spawn: $145/$146 Sluggy stomp puff (Bank07:7214 in BlueSluggy/PinkSluggy_StompRt); $0D2 MardingMilde state_01_eat_yoshi cinematic puff (Bank04:10289); inflating-balloon phase-8 pop (Bank03:13958 CODE_03EA89); Bank0F:3599. Also Burt-the-Bashful GSU command-buffer entry (Bank06:4416). Notes: previous "lightning-Lakitu generator end" label was positional inference.
!Define_YI_AmbSpr1EF = $01EF	; Baron Von Zeppelin carry-cargo trail particle: CODE_009531 stride-2 timer (freeze + dec $73C2 with hold 2) then despawn. Spawn: heavily used by the Baron Von Zeppelin family ($177-$17F): 9 per-frame trail-particle sites across Bank07 (Bank07:14549 + 14631 + 14660 + 14795 + 14917 + 15337 + 15372 + 15403 + 15520 -- one per carry-variant handler). Also reused as a fade-out puff by two normal-sprite Main routines: Bank0C:7127 inside YI_NorSpr1A2_HealthStar_Main (HealthStar despawn puff) and Bank0D:8581 inside YI_NorSpr10B_HoppingSilverTapTap_Main (Tap-Tap fade).
!Define_YI_AmbSpr1F0 = $01F0	; IcyWatermelon freeze-shard particle: 7-stage animation (DATA_009614 tiles 4-3-2-1-0-0-0, uniform hold 4) then despawn -- a short fade-down trail. Spawn: ice-melon-freeze RNG-jittered ice-shard helper (Bank03:7378 inside CODE_03B5C3) called only from $005 IcyWatermelon-Main (Bank04:240); single producer.
!Define_YI_AmbSpr1F1 = $01F1	; Baby Bowser arena puff (closer cinematic): CODE_009531 stride-2 placeholder timer + despawn. Spawn: Bank0D:1794 + 3006 (Bowser-fight / closer cinematic puff sites in Bank0D Baby Bowser area). Notes: previous "mini-Piranha generator start" label was positional inference.
!Define_YI_AmbSpr1F2 = $01F2	; Break-frozen-enemy puff (universal): SuperFX-rendered multi-frame burst via FXCODE_098CB1 reading DATA_009693 (12-entry pointer table of per-stage tile-blob lists DATA_009868..DATA_0096AB); per-frame body decs $73C2 from $0B->0 (11 stages), indexing DATA_009688 (per-stage attribute byte written to $7001) and DATA_00963B (hold times 4,4,4,4,4,4,4,3,3,2,2). Spawn: break-frozen-enemy puff helper CODE_03B595 at ROM $03:B595 (Bank03 line 7329) -- 6 callers (Bank03 stomp + egg-hit + monkey + Bank0C:472 level-load); also Mini-Piranha bud (Bank0C:472). Notes: previous "mini-Piranha generator end" label was positional inference.
!Define_YI_AmbSpr1F3 = $01F3	; Crate-break shrapnel (rotating): SuperFX OAM-attribute-rotator (DATA_0095A4/0095B8 masks) per-frame XORs into OAM byte 4, animates 10-step rotation around $7E4E; spinning/rotating effect. Spawn: $003/$10E Crate-break shrapnel (Bank0D:2416 + 2590 in CrateWithKey/CrateWith6Stars_Main).
!Define_YI_AmbSpr1F4 = $01F4	; Georgette Jelly drip-drop puff: CODE_009531 stride-2 placeholder timer + despawn. Spawn: $111 Georgette Jelly drip-drop puff (Bank01:4992 in GeorgetteJelly_Main; single spawn site).
!Define_YI_AmbSpr1F5 = $01F5	; Snifit projectile-spawn smoke puff (V1.1 extension area): generic OAM frame stepper (CODE_00986D): per-frame, when $7782 hits 0, increment $73C2 and reload $7782 from $7E4C; loops until $7E4E counter underflows -- indefinite cycler. Spawn: $113 Snifit projectile-spawn smoke puff (Bank07:2684 in Snifit_Main; single spawn site).
!Define_YI_AmbSpr1F6 = $01F6	; Snifit / GreenGlove attack puff: same generic OAM frame stepper as $1F5 (CODE_00986D) -- indefinite cycler. Spawn: $113 Snifit secondary projectile puff (Bank07:2733); $11A GreenGlove attack puff (Bank07:4613 GreenGlove_Main). Notes: previous "balloon-bomb generator end" label was positional inference.
!Define_YI_AmbSpr1F7 = $01F7	; ShyguyOnStilts wobble/balance/fall puff: CODE_009519 freeze-only stub (no $73C2 work; lifetime via $7782 -> CODE_008AF2 despawn). Spawn: $0F2 ShyguyOnStilts wobble/balance/fall puff (Bank07:803 + 1030 + 1092 -- all in ShyguyOnStilts_Main).
!Define_YI_AmbSpr1F8 = $01F8	; Lakitu cloud-trail particle (regular / Aqua / Thunder variants): CODE_00958D stride-8 timer (freeze + dec $73C2 with hold 8) then despawn -- slow fade. Spawn: $11B Lakitu / $170 AquaLakitu / $166 ThunderLakitu cloud-trail particles (Bank07:5034 Lakitu_Main + 13518 ThunderLakitu_Main); also Bank0D:8063 + Bank0E:15124 (BabyBowser arena clouds).
!Define_YI_AmbSpr1F9 = $01F9	; GreenGlove ambient projectile particle: CODE_00986D generic indefinite OAM cycler (same as $1F5/$1F6) -- visible-while-active marker. Spawn: $11A GreenGlove ambient projectile particle (Bank07:4657 in GreenGlove_Main; single spawn site).
!Define_YI_AmbSpr1FA = $01FA	; HorizontalLavaDrop droplet trail puff (paired with $1FB): CODE_009576 stride-6 timer (freeze + dec $73C2 with hold 6) then despawn. Spawn: $12F HorizontalLavaDrop droplet trail puff (Bank07:5480 in HorizontalLavaDrop_Main; single spawn site).
!Define_YI_AmbSpr1FB = $01FB	; VerticalLavaDrop droplet trail puff (paired with $1FA): CODE_009576 stride-6 timer -- same body as $1FA. Spawn: $130 VerticalLavaDrop droplet trail puff (Bank07:5641 in VerticalLavaDrop_Main; single spawn site).
!Define_YI_AmbSpr1FC = $01FC	; DanglingFang descent / attack puff: CODE_009519 freeze-only stub (no $73C2 work; lifetime via $7782 -> CODE_008AF2 despawn). Spawn: $13D DanglingFang descent / attack puff (Bank07:6161 in DanglingFang_Main; single spawn site).
!Define_YI_AmbSpr1FD = $01FD	; FlopsyFish jump-splash puff: CODE_009548 stride-3 countdown + despawn (placeholder timer slot, no visible body). Spawn: $140 FlopsyFish jump-splash puff (Bank07:6655 in FlopsyFish_Main; single spawn site).
!Define_YI_AmbSpr1FE = $01FE	; FlopsyFish jump-arc anticipation flash: 6-frame symmetric bell-curve hold (CODE_009416 at Bank00:2737, DATA_009410: 2,4,6,A,6,4): cycles $73C2 through 6 OAM tiles with hold table giving slow-fast-slow timing; visible flash/spark. Spawn: $140 FlopsyFish jump-arc anticipation flash (Bank07:6634 + 6779 FlopsyFish_Main); MelonBug-area effect (Bank05:16251); also GSU IWT path (SuperFX Bank08:6103).
!Define_YI_AmbSpr1FF = $01FF	; Goonie aerial-patrol companion: wandering generator (CODE_009ADD): applies physics, toggles X-velocity sign every $40 frames via DATA_009AD9 (-$40/+$40); patrol-style movement; auto-despawns on $7E8E expiry. Spawn: $0E8/$0E9/$153 Goonie aerial-patrol ambient companion (Bank0E:2890 in Goonie_Main; single spawn site). See docs/family-goonies.md.
!Define_YI_AmbSpr200 = $0200	; RotatingArrowCloud charge-up sparkle: slide-charge buildup (CODE_009B13): increments $7E8C accumulator using $7E4E delta until carry into key $7462=$FF, ramps $7E4E by 4 per frame to $100 cap -- a charging-then-snap effect. Spawn: $151 RotatingArrowCloud charge-up sparkle (Bank07:7432 in RotatingArrowCloud_Main; single spawn site).
!Define_YI_AmbSpr201 = $0201	; AquaLakitu fishing-rod water splash: CODE_009531 stride-2 countdown + despawn (placeholder timer slot). Spawn: $170 AquaLakitu fishing-rod water splash (Bank07:13163 in AquaLakitu_Main); also Bank07:13180 ($1BA pickup) adjacent. Also GSU IWT paths (SuperFX Bank0A:4428 + 5100 + Bank0B:11251 + 11956).
!Define_YI_AmbSpr202 = $0202	; Flutter spore-drift sparkle (paired with $203): CODE_009519 freeze-only stub (JSR check_amb_sprite_freeze_no_pull / RTS -- no $73C2 work; lifetime ticks via $7782 then despawn through CODE_008AF2). Spawn: $152 Flutter spore-drift sparkle (Bank07:7618 in Flutter_Main; single spawn site).
!Define_YI_AmbSpr203 = $0203	; Flutter secondary spore particle (paired with $202): CODE_009531 stride-2 countdown + despawn (placeholder timer slot). Spawn: $152 Flutter secondary spore particle (Bank07:7793 in Flutter_Main; single spawn site).
!Define_YI_AmbSpr204 = $0204	; SprayFish water-spray particle (stage A): CODE_009531 stride-2 countdown + despawn (placeholder timer slot). Spawn: $143 SprayFish water-spray particle stage A (Bank07:8251 in SprayFish_Main).
!Define_YI_AmbSpr205 = $0205	; SprayFish water-spray particle (stage B): CODE_00955F stride-4 countdown + despawn (placeholder timer slot). Spawn: $143 SprayFish water-spray particle stage B (Bank07:8294 in SprayFish_Main).
!Define_YI_AmbSpr206 = $0206	; SprayFish water-spray particle (stage C): 2-frame countdown OAM tile walk (DATA_009B53 = $0C,$10): cycle $73C2 through 2 OAM tiles with holds 12/16 -- short hold sparkle. Spawn: $143 SprayFish water-spray particle stage C (Bank07:8181 in SprayFish_Main; paired with $204 + $205 above).
!Define_YI_AmbSpr207 = $0207	; Grunt walking-dust trail: CODE_009519 freeze-only stub (JSR check_amb_sprite_freeze_no_pull / RTS -- no $73C2 work; lifetime ticks via $7782 then despawn through CODE_008AF2). Spawn: $159/$15A WalkingGrunt/RunningGrunt walking-dust trail (Bank07:9118 in Grunt_Main; single spawn site).
!Define_YI_AmbSpr208 = $0208	; Enemy death-pop OAM (universal): 22-stage long animation (DATA_009B72) with mid-animation OAM-attribute swap at stage $16 (sets $7462=$FF for one frame), holds 3 then 2. Spawn: shared helper CODE_03B4D6 at Bank03:7239; ~6 callers including Bank03:4261 (CODE_spr_state_die_collision death tail), Bank03:5385 (egg-collision death), Bank03:7794 + 9912; Bank0C:11579 + 16165.
!Define_YI_AmbSpr209 = $0209	; BlowHard wind sparkle: twin-counter despawn (CODE_009BBC): two timers ($7782, $7E8E) gate stage transitions; $73C2 cycles 5..-1 with $7E8E reset to 4 each stage; despawns on $7782=0. Spawn: $0F8/$04C BlowHard wind sparkle (Bank0E:6152 in BlowHard_Main; single spawn site).
!Define_YI_AmbSpr20A = $020A	; ZeusGuyBlast lightning-impact mirror-flash: 5-stage countdown (DATA_009BDE = 8,6,4,2,2) with stage-3 sign-flip of $7462 (sets -1 then back to +1); OAM mirror/flip cue inside a vanish. Spawn: $0FE ZeusGuyBlast lightning-impact mirror-flash (Bank07:11145 in ZeusGuyBlast_Main); also GSU IWT path (SuperFX Bank0A:5702).
!Define_YI_AmbSpr20B = $020B	; ChompRock smash debris: SuperFX multi-tile renderer (CODE_009C1D at Bank00:3590, 13-entry DATA_009C6B pointer list, FXCODE_098CB1 plot pass): walks $73C2 down through 13 stages reading per-stage attribute byte from DATA_009C5F and hold time from DATA_009C11. Sizable progressively-expanding tile cluster -- similar shape to $1F2 but bigger. Spawn: $09E ChompRock smash debris (Bank0E:9130 in ChompRock_Main); also GSU IWT path (SuperFX Bank0A:5875).
!Define_YI_AmbSpr20C = $020C	; Hookbill-arena / ChompRock destruction debris: SuperFX multi-tile renderer (CODE_009E92 at Bank00:3696, 14-entry DATA_009EE0 pointer list, FXCODE_098CB1 plot pass): walks $73C2 down through 14 stages reading per-stage attribute byte from DATA_009ED3 with hardcoded hold $02 each step. Similar shape to $20B but different art (larger arena debris). Spawn: Hookbill closer_salvo arena-rock destruction debris (Bank01:4515 -- post-Hookbill arena collapse); ChompRock destruction paired with $20B (Bank0E:9109 ChompRock_Main); also GSU IWT path (SuperFX Bank0A:5798).
!Define_YI_AmbSpr20D = $020D	; ThunderLakitu lightning-bolt sparkle (paired with $20E): CODE_009519 freeze-only stub (JSR check_amb_sprite_freeze_no_pull / RTS -- no $73C2 work; lifetime ticks via $7782 then despawn through CODE_008AF2). Spawn: $166 ThunderLakitu lightning-bolt sparkle (Bank07:13699 + 13784 in ThunderLakitu_Main).
!Define_YI_AmbSpr20E = $020E	; ThunderLakitu lightning-bolt sparkle (paired with $20D): CODE_009519 freeze-only stub (JSR check_amb_sprite_freeze_no_pull / RTS -- no $73C2 work; lifetime ticks via $7782 then despawn through CODE_008AF2). Spawn: $166 ThunderLakitu lightning-bolt paired sparkle (Bank07:13720 in ThunderLakitu_Main; single spawn site).
!Define_YI_AmbSpr20F = $020F	; ThunderLakituFireball impact-blink: 2-frame latched OAM tile decrement (CODE_00951D): sets $7782=1 then dec $73C2 each tick; despawns when underflows -- minimal 2-tile blink. Spawn: $0A2 ThunderLakitu Fireball impact-blink (Bank0E:6462 in ThunderLakituFireball_Main; single spawn site).
!Define_YI_AmbSpr210 = $0210	; Mufti-Guy flower-disguise petal burst: SuperFX multi-tile renderer (CODE_00A193 at Bank00:3816, 24-entry DATA_00A1E9 pointer list, FXCODE_098CB1 plot pass): walks $73C2 down through 23 stages reading attribute byte from DATA_00A1D2 and hold time from DATA_00A17C (mostly hold-$04 tapering to 1); very long-duration tile-cluster animation. Spawn: CODE_mufti_guy_burst_petals (Bank04:3130 -- spawns the flower petals when attacking a flower guy); also Bank07:15736 (boss-closer arena).
!Define_YI_AmbSpr211 = $0211	; Goonie attack-burst petals: same body as $210 (CODE_00A193 at Bank00:3816) -- 23-stage SuperFX expansion via 24-entry DATA_00A1E9 / DATA_00A1D2 attribute / DATA_00A17C hold. Spawn: $0E8 Goonie attack-burst petals (Bank0E:3209 in Goonie_Main); also Bank07:15732 (boss-closer arena, paired with $210). See docs/family-goonies.md.
!Define_YI_AmbSpr212 = $0212	; Crazee Dayzee "happy notes" emote: per-frame logic (CODE_00A551 at Bank00:3971) is a 2-bin sign-pick from 4-entry DATA_00A54D: if AmbSpr Y-position $7142 < threshold $7E4C then write $00F8 to $75A2 (X-velocity register) else $0008 -- drifts left/right depending on whether the note is above or below its anchor. Spawn: CODE_0F85FC (Bank0F:789) called every $20 frames during $181 Crazee Dayzee state $00 (walking) at Y-offset -16. See docs/family-misc.md §3.
!Define_YI_AmbSpr213 = $0213	; WatermelonFlame smoke trail (fire-watermelon): 8-stage countdown (CODE_00A56F at Bank00:3989) walking $73C2 down with per-stage hold from DATA_00A567 (7,7,5,4,4,4,4,4), then despawn -- mid-length puff. Spawn: $018 WatermelonFlame smoke trail (Bank04:565 in WatermelonFlame_Main; single spawn site).
!Define_YI_AmbSpr214 = $0214	; GSU-only multi-tile burst (no SNES spawn): SuperFX multi-tile renderer (CODE_00A59A at Bank00:4011, 15-entry DATA_00A5EB pointer list, FXCODE_098CB1 plot pass): walks $73C2 down through 15 stages reading per-stage attribute byte from DATA_00A5DC and hold time from DATA_00A58C (6/5/4 pattern); medium-size progressive burst. Spawn: only GSU IWT paths (SuperFX Bank0A:5993 + Bank0B:11084); GSU-only.
!Define_YI_AmbSpr215 = $0215	; Skeleton Goonie patrol companion: wandering generator (CODE_009ADD reuse): same physics+sign-flip body as $1FF; patrol-style movement, $40-frame direction cycle. Spawn: $19D SkeletonGoonie patrol companion (Bank0C:3797 in SkeletonGoonie_Main; single spawn site -- same wandering-helper pattern as $1FF for regular Goonie). See docs/family-goonies.md.
!Define_YI_AmbSpr216 = $0216	; Skeleton Goonie wing-loss puff: 2-phase trigger (CODE_00A6A9): waits for $7782=0 then alternates $7E8E flag; decrements $73C2 once per cycle, reloads from $7E4C; despawns when $7782=0 reaches early gate. Spawn: $19D SkeletonGoonie wing-loss puff via CODE_0C9C7B helper (Bank0C:3753 + 3857 + 4079 -- 3 callers in SkeletonGoonie_Main). See docs/family-goonies.md.
!Define_YI_AmbSpr217 = $0217	; Salvo the Slime droplet ground-bounce: conditional vanish on Y-speed (CODE_00A6CE): if $7820 LSB set, set $6F62=$1C and ramp $73C2; if YSpeed < $40 then despawn, otherwise invert YSpeed (bounce). Ground-impact bounce-then-vanish. Spawn: $02D Salvo the Slime droplets that splash & bounce on impact (Bank06:1102 + 1601 in SalvoTheSlime_Main).
!Define_YI_AmbSpr218 = $0218	; BowserFightGiantEgg bounce-debris (final boss fight): SuperFX 4x6=24-frame OAM renderer (CODE_00A835, DATA_00A8AE list of 24+ tile blobs, FXCODE_098CB1 and FXCODE_09F5F4 plot pass): animates an OAM-shrink burst with $7E4E-driven OAM-tile-attribute variant select; large multi-art effect. Spawn: $026 BowserFightGiantEgg bounce-debris (Bank0D:13264 in BowserFightGiantEgg_Main; single spawn site).
!Define_YI_AmbSpr219 = $0219	; Little Skull Mouser appearance/disappearance puff: same body as $216 (CODE_00A6A9) -- 2-phase trigger / dual-timer pulse. Spawn: $1A3 LittleSkullMouser appearance/disappearance puff (Bank0C:7059 in LittleSkullMouser_Main; single spawn site).
!Define_YI_AmbSpr21A = $021A	; KeyholeCork pop-out puff: 12-stage rich animation (CODE_00A726 at Bank00:4162, three parallel 12-entry tables): DATA_00A702 -> $73C2 tile (10..0..0), DATA_00A70E -> $7782 hold (4,4,3,3,2,2,1,...), DATA_00A71A -> $7462 attribute (mostly $01, with $FF at stage 10 for mid-anim flip cue). Visible despawn with mirror-flip cue. Spawn: $1A4 KeyholeCork pop-out puff (Bank07:15875 in KeyholeCork_Main; single spawn site).
!Define_YI_AmbSpr21B = $021B	; HotLips fire-blast smoke (paired with $21E): 2-frame countdown OAM walk (CODE_009B55, DATA_009B53) -- same body as $206. Spawn: $1AA HotLips fire-blast smoke (Bank0C:8045 in HotLips_Main; single spawn site).
!Define_YI_AmbSpr21C = $021C	; GSU-only timed puff (no SNES spawn): 9-stage countdown (CODE_00A759 at Bank00:4188, 9-entry DATA_00A750 holds 3,3,3,3,3,3,3,2,2): cycle $73C2 down with mostly hold-3 then despawn. Spawn: only a GSU IWT path (SuperFX Bank0B:12014); GSU-only.
!Define_YI_AmbSpr21D = $021D	; GSU-only timed decrement (no SNES spawn): 3-frame stride OAM decrement (CODE_00A776): reload $7782=3 each step, dec $73C2, despawn on underflow. Spawn: only a GSU IWT path (SuperFX Bank0B:12046); GSU-only.
!Define_YI_AmbSpr21E = $021E	; HotLips fire-blast secondary smoke (paired with $21B): CODE_009519 freeze-only stub (JSR check_amb_sprite_freeze_no_pull / RTS -- no $73C2 work; lifetime ticks via $7782 then despawn through CODE_008AF2). Spawn: $1AA HotLips fire-blast secondary smoke (Bank0C:8107 in HotLips_Main; single spawn site).
!Define_YI_AmbSpr21F = $021F	; Raphael the Raven death-twinkle sparkle: 4-frame stride OAM decrement (CODE_00A78D): reload $7782=4 each step, dec $73C2, despawn on underflow. Spawn: $174 Raphael the Raven death-twinkle sparkle in CODE_raphael_state_main_death_fade_to_twinkle (Bank0F:7147; single spawn site).
!Define_YI_AmbSpr220 = $0220	; Kamek (cutscene) magic-spell sparkle: 4-frame stride OAM walk (CODE_00A7A4) with attribute-byte $7462 set to 1, stage-$01 wrap Y nudge by +$08 -- short bobbing vanish. Spawn: $048 CutsceneKamek magic-spell sparkle particles (Bank0C:12603 + 12703 in CutsceneKamek_Main).
!Define_YI_AmbSpr221 = $0221	; Prince Froggy StomachAcid drip splash: 2-frame stride OAM decrement (CODE_00A7F7): reload $7782=2 each step, dec $73C2, despawn on underflow. Spawn: $13B Prince Froggy StomachAcid acid-drip splash (Bank02:8955 in StomachAcid_Main; single spawn site).
!Define_YI_AmbSpr222 = $0222	; Naval Piranha defeat-debris dirt chunk: CODE_009531 stride-2 countdown + despawn (placeholder timer slot). Spawn: $171 Naval Piranha defeat-debris dirt chunk via CODE_naval_pir_spawn_debris_chunk (Bank02:13757; single spawn site).
!Define_YI_AmbSpr223 = $0223	; Hookbill the Koopa dead-pancake squish particles: CODE_009519 freeze-only stub (JSR check_amb_sprite_freeze_no_pull / RTS -- no $73C2 work; lifetime ticks via $7782 then despawn through CODE_008AF2). Spawn: $0AE Hookbill the Koopa dead-pancake squish particles (Bank01:3962 inside CODE_01A181, called as part of the post-Hookbill_dead_pancake death animation).
!Define_YI_AmbSpr224 = $0224	; Sniff-detect sparkle: physics-tick-only stub (CODE_00A80E): JSR CODE_008AF2 which decrements lifetime and despawns when zero; physics still applied (no freeze short-circuit). Spawn: spawned inside the shared "is Yoshi within sniff radius?" helper CODE_02D985 (Bank02:10267); CODE_02D985 is called from $0D1 SecretPipeEntrance_Main (Bank02:10148, Y=$02 sniff radius) and from the Winged-Cloud sniff path (Bank03:8977 + Bank03:9073, Y=$02). NOT spawned by horizontal-pipe entrances $0D0/$147 -- their Main path calls CODE_02CDB9 directly and never enters CODE_02D985.
!Define_YI_AmbSpr225 = $0225	; Dormant placeholder timer (no observed spawn): CODE_009519 freeze-only stub (no $73C2 work; lifetime via $7782 -> CODE_008AF2 despawn). Spawn: (no runtime spawn site found -- handler is dormant in the dispatch table).
!Define_YI_AmbSpr226 = $0226	; Coin-pickup spinning-coin popup: 2-bit cycle through 4 OAM tiles, mapped from global timer $14 (LSR x3 + AND #3); freeze-without-pulling; renders the spinning coin-get sparkle. Spawn: coin-pickup spinning-coin popup via shared helper CODE_03A4F5 (Bank03:5103) called from the GSU coin-collection path at Bank00:9917 (CODE_00DFE2 area, same dispatch as the $1E4 coin sparkle).
!Define_YI_AmbSpr227 = $0227	; BowserRoomKamek magic-spell launch sparkle: 3-stage animation with physics (CODE_00921A reuse): same shape as $1DB, 3 OAM tiles with uniform hold-8. Spawn: $08E BowserRoomKamek magic-spell launch sparkle (Bank0D:11981 in BowserRoomKamek_Main; single spawn site).
!Define_YI_AmbSpr228 = $0228	; ZeusGuy lightning-spark particle: CODE_009519 freeze-only stub (JSR check_amb_sprite_freeze_no_pull / RTS -- no $73C2 work; lifetime ticks via $7782 then despawn through CODE_008AF2). Spawn: $0FD ZeusGuy lightning-spark particle (Bank07:10511 in ZeusGuy_Main; single spawn site).
!Define_YI_AmbSpr229 = $0229	; WatermelonSeed projectile trail dust: CODE_009519 freeze-only stub (JSR check_amb_sprite_freeze_no_pull / RTS -- no $73C2 work; lifetime ticks via $7782 then despawn through CODE_008AF2). Spawn: $107 WatermelonSeed projectile trail dust (Bank01:5743 in WatermelonSeed_Main; single spawn site).
!Define_YI_AmbSpr22A = $022A	; CoinCannon firing-blast cone (bonus game): SuperFX multi-stage spawner (CODE_0098AC): pushes coords/OAM index to GSU via FXCODE_089287; walks 5-stage tables DATA_009884/00988E/009898/0098A2 advancing the stage every $7E8E underflow; despawn on stage end. Spawn: $1B1 CoinCannon firing-blast cone (Bank11:5520 in CoinCannon_Main; single spawn site).
!Define_YI_AmbSpr22B = $022B	; Bandit-minigame jackpot row head (CODE_009913 at Bank00:3206): 15-stage tile cycler walking $73C2 via 15-entry DATA_00997A; at stage 14 calls CODE_00995F (Bank00:3240) which spawns AmbSpr $22D as the jackpot popup tail and via CODE_009A96 (Bank00:3380) queues SoundID08_1up + sets the popup positional offsets. Spawn (Bank11 minigame): CODE_11A22B at Bank11:3622-3628 (jackpot-only path -- sets $10E2=$10E6=1 then spawns $22B); CODE_11A527 at Bank11:4032 (jackpot fallback after spawning $22E directly); CODE_11A61A at Bank11:4116 is the RNG that returns $22B (jackpot) or $22C (regular). Note: prior label said the chain is linear $22B->$22C->$22D->$22E -- it actually splits into two parallel jackpot/regular chains and Bank11 spawns $22B/$22C/$22E directly.
!Define_YI_AmbSpr22C = $022C	; Bandit-minigame regular-row head (CODE_009998 at Bank00:3259): cycles $73C2 through 4-entry DATA_009A08 with per-stage holds from DATA_009A10; when AmbSpr YSpeed crosses #$0280 (Bank00:3280) zeroes the lifetime timer; otherwise on first frame ($7E8C=0) spawns AmbSpr $22E via JSL CODE_spawn_ambient_sprite at Bank00:3290 then queues SoundID3F_HitUvula via CODE_009ABF (Bank00:3398). Spawn: CODE_11A527 at Bank11:3979 (returned from CODE_11A61A when not the jackpot path); not chained from $22B -- this is the regular-row equivalent head.
!Define_YI_AmbSpr22D = $022D	; Bandit-minigame jackpot popup tail (CODE_009A19 at Bank00:3318): cycles $7E4E stage 4..$0B with per-stage holds (parity-based reload from $7E4E&1) and on first frame ($7E8E=0) does a JSL CODE_1191B8 (Bank00:3346) then writes slot index back to $7E4A. IMPORTANT: CODE_1191B8 is the Bandit-minigame STATE-MACHINE DISPATCHER (Bank11:1965) which jumps via 3-entry DATA_1191D9 (CODE_11922A / CODE_1192B6 / CODE_1191DF) indexed by state $10E2 -- it advances the minigame scene, NOT a 1up award (the 1up SFX was already queued by $22B's CODE_009A96 helper). Spawn: only via $22B's CODE_00995F internal chain at Bank00:3241 -- no direct Bank11 caller.
!Define_YI_AmbSpr22E = $022E	; Bandit-minigame final fade -- last allocated ambient ID (CODE_009A66 at Bank00:3356): 8-stage countdown cycling $7E4E 0..7 with uniform hold 3 (reloads $7E4C=3 each step), zeroes $7782 to despawn on stage 8. Spawn: chained internally from $22C's CODE_009998 at Bank00:3290 (regular-row tail); also spawned directly from Bank11:4016 (CODE_11A527 prep path -- when jackpot RNG returns $22B but state $10E2=0, spawns $22E first then falls into $22B spawn at line 4032).

; -- Engine-reserved / unallocated entries (sparse, gaps deliberate) ----------
!Define_YI_AmbSpr22F_Invalid = $022F	; Unallocated slot -- no handler in V1.0/V1.1.
!Define_YI_AmbSpr233_Invalid = $0233	; Unallocated slot -- no handler in V1.0/V1.1.
!Define_YI_AmbSpr236_Invalid = $0236	; Unallocated slot -- no handler in V1.0/V1.1.
!Define_YI_AmbSpr244_Invalid = $0244	; Unallocated slot -- no handler in V1.0/V1.1.
