;#############################################################################################################
;# ObjectIDs.asm -- Standard-object IDs ($00-$F6).
;#
;# Dispatch table:  DATA_standard_object_init_ptrs (in yi/Banks/Bank12.asm).
;#                  247 16-bit entries (rows $00-$F6), each a Bank12 init-handler address minus $01
;#                  (PHA/RTS trampoline contract). Indexed directly by std-object ID.
;#                  IDs $F7-$FF do not exist as dispatch entries -- their property-table bytes are
;#                  $FF (sentinel). $FF is reserved by the engine as the screen-exit-record marker
;#                  in the level-data stream (handled separately by CODE_108C33 in Bank10).
;# Property table:  DATA_1284EC / DATA_object_property_table (also in Bank12.asm) carries the
;#                  per-ID 2-bit width-mode encoding consumed by the Bank10 stream-decoder.
;#
;# Object ID space split:
;#   $00-$F6  standard objects -- this file. Each ID's init handler typically sets up walker
;#            context and JMPs to CODE_12A3DB with a Bank13 cell-stamp body pointer; the walker
;#            iterates the row x col rectangle from the level stream and calls the Bank13
;#            stamper per cell. Zero vestigial slots -- every ID has a live handler.
;#   $00 stream prefix + extended-byte  extended objects -- see ExtendedObjectIDs.asm.
;#            (Stream byte = $00 signals an extended-object record; next byte is the ext-ID.)
;#
;# Naming convention:  the per-ID names below are DERIVED FROM HANDLER-BODY BEHAVIOUR (the Bank12
;# init body and its Bank13 stamper target), not from any external nomenclature. Where a Bank12
;# init handler has already been promoted to a CODE_init_* alias, the descriptive part of the
;# define name is taken from that alias. For raw CODE_xxxxxx handlers we walked the body and
;# named after the dominant tile/shape effect of the stamper. Many IDs share one handler (e.g.
;# $02/$03 + $0A/$0B all route into the floor-edge/wall dispatcher CODE_init_floor_edge_or_wall),
;# and a few handlers are shared across non-adjacent IDs (e.g. $57 + $7E both into
;# CODE_init_seven_segment_decor; $68 + $8A both into CODE_init_coin_object).
;#
;# See also (sibling reference files):
;#   yi/Banks/Bank12.asm           -- the dispatch table itself + all init handlers
;#   yi/Banks/Bank13.asm           -- the cell-stamp bodies the inits jump to
;#   docs/leveldataengine.md       -- engine overview (object/sprite stream format, walker, Map16)
;#############################################################################################################

!Define_YI_StdObj00_ScreenExitClear = $0000	; Init Bank12:2729 (CODE_init_screen_exit_clear) | Special non-tile-stamp: clears the 256-entry screen-num-to-exit map at $7E:6CAA, zeroes a 512-byte screen-exit destination block at $7F:8000+(screen_id*$200), and decrements live-exit count $0D4D. Dispatched by std-object table but does not drive the walker.
!Define_YI_StdObj01_FloorBasic = $0001	; Init Bank12:2770 (CODE_init_floor_basic); Stamp Bank13:175/194/310 | THE basic ground/ledge -- the most common ground object. Variable width x height (from the object's size bytes; NOT a fixed 3-wide). Walker fills column-by-column: even cols use the left-half surface/dirt tiles (CODE_bg_floor_left), odd cols the right-half (CODE_bg_floor_right), giving a 2-tile repeating surface texture. $19=3 is a per-column ROW threshold: rows 0-2 use those deterministic tiles, rows >=3 switch to random grass fill (CODE_bg_floor_random) -- so the random handler only fires on floors >=4 tall. Init shifts the row origin up 1 tile and grows the object 1 taller (INC $2E).
!Define_YI_StdObj02_FloorEdgeLeft = $0002	; Init Bank12:2804 (CODE_init_floor_edge_or_wall); Stamp Bank13:443 | Shared 4-variant dispatcher with $03/$0A/$0B. Indexes DATA_129286/DATA_129290/DATA_1292A4 (3 parallel 10-entry tables) by orientation $15 to pick CODE_floor_edge_left_right (1381CA) for $02/$03 or CODE_wall_left_right for $0A/$0B; bumps row origin up by 1 for the edge tile.
!Define_YI_StdObj03_FloorEdgeRight = $0003	; Init Bank12:2804 (CODE_init_floor_edge_or_wall); Stamp Bank13:443 | Shared with $02/$0A/$0B (4-variant dispatcher). Right-edge variant of the floor-edge stamp; same handler as $02 with $15 selecting the right-side tile from DATA_129286.
!Define_YI_StdObj04_FloorSlope22DegDown = $0004	; Init Bank12:2880 (CODE_init_floor_slope_22deg); Stamp Bank13:611 (CODE_floor_slope_22deg) | 22.5-deg DOWN slope (descends left-to-right, 1:2). Init applies row-up shift (CODE_floor_row_shift_up); $15 bit 0 = 0 -> picks $17=$FFFF (negative step = descending) from DATA_1292B8; keep-slope walker. Shared with $05 (the UP variant, bit 0 = 1). [Direction verified by render; name was reversed.]
!Define_YI_StdObj05_FloorSlope22DegUp = $0005	; Init Bank12:2880 (CODE_init_floor_slope_22deg); Stamp Bank13:611 | 22.5-deg UP slope (ascends left-to-right, 1:2). $15 bit 0 = 1 -> $17=$0001 (positive step = ascending). Shares handler with $04. [Direction verified by render; name was reversed.]
!Define_YI_StdObj06_FloorSlope45DegDown = $0006	; Init Bank12:2899 (CODE_init_floor_slope_45deg); Stamp Bank13:677/708 | 45-deg DOWN slope (descends left-to-right, 1:1). Shared init for $06-$09; index ($15-4)*2 into DATA_129322/DATA_12932E -> width $19=4, $17=$FFFF (-1 = descending). Stamps CODE_floor_slope_45deg_up/_down + random fill. [Angle+direction verified by render; both were mislabeled.]
!Define_YI_StdObj07_FloorSlope45DegUp = $0007	; Init Bank12:2899 (CODE_init_floor_slope_45deg); Stamp Bank13:677/708 | 45-deg UP slope (ascends left-to-right, 1:1). Width $19=4, $17=$0001 (+1 = ascending). UP variants ($07/$09) take the 2nd row-shift path. Shares handler with $06/$08/$09. [Angle+direction verified by render; both were mislabeled.]
!Define_YI_StdObj08_FloorSlope67DegDown = $0008	; Init Bank12:2899 (CODE_init_floor_slope_45deg); Stamp Bank13:677/708 | 67.5-deg DOWN slope (descends left-to-right, 2:1 steep). Width $19=5, $17=$FFFE (-2 = descending). Shares handler with $06/$07/$09. [Angle+direction verified by render; both were mislabeled.]
!Define_YI_StdObj09_FloorSlope67DegUp = $0009	; Init Bank12:2899 (CODE_init_floor_slope_45deg); Stamp Bank13:677/708 | 67.5-deg UP slope (ascends left-to-right, 2:1 steep). Width $19=5, $17=$0002 (+2 = ascending). UP variants ($07/$09) take the 2nd row-shift path. Shares handler with $06/$07/$08. [Angle+direction verified by render; both were mislabeled.]
!Define_YI_StdObj0A_WallLeftEdge = $000A	; Init Bank12:2804 (CODE_init_floor_edge_or_wall); Stamp Bank13:765 (CODE_wall_left_right) | Vertical wall left edge. Shares the 4-variant dispatcher with $02/$03/$0B; $15 selects CODE_wall_left_right and the left-side tile.
!Define_YI_StdObj0B_WallRightEdge = $000B	; Init Bank12:2804 (CODE_init_floor_edge_or_wall); Stamp Bank13:765 (CODE_wall_left_right) | Vertical wall right edge. Shares the 4-variant dispatcher with $02/$03/$0A; $15 selects the right-side tile.
!Define_YI_StdObj0C_PostVertical = $000C	; Init Bank12:2961 (CODE_init_post_vertical); Stamp Bank13:791 (CODE_post_vertical_3section) | Vertical post / stake (3-section). Trampoline-walker init; extent comes from the object stream's size bytes. Shared with $0E/$0F.
!Define_YI_StdObj0D_PostHorizontal = $000D	; Init Bank12:2968 (CODE_init_post_horizontal); Stamp Bank13:846 (CODE_post_horizontal_3section) | Horizontal bouncing-post / trampoline bar (3-section).
!Define_YI_StdObj0E_SkiLiftPoleLeft = $000E	; Init Bank12:2961 (CODE_init_post_vertical); Stamp Bank13:791 (CODE_post_vertical_3section) | Left support pole of a ski-lift wire. Variant $15&3=2 of the shared vertical-post stamp (variant = object-ID low bits); draws tiles $0091 (top) / $0095 (mid). Shares handler with $0C (plain vertical post) and $0F (right pole).
!Define_YI_StdObj0F_SkiLiftPoleRight = $000F	; Init Bank12:2961 (CODE_init_post_vertical); Stamp Bank13:791 (CODE_post_vertical_3section) | Right support pole of a ski-lift wire. Variant $15&3=3 of the shared vertical-post stamp (variant = object-ID low bits); draws tiles $0090 (top) / $0094 (mid). Shares handler with $0C (plain vertical post) and $0E (left pole).
!Define_YI_StdObj10_LiftTrack30Deg = $0010	; Init Bank12:2975 (CODE_init_lift_track_30deg); Stamp Bank13:918 (CODE_lift_track_30deg) | 30-deg moving-platform rail. Forces extent $2E=2 and slope step $17=$FFFF; keep-slope walker.
!Define_YI_StdObj11_LiftTrack45Deg = $0011	; Init Bank12:2986 (CODE_init_lift_track_45deg); Stamp Bank13:992 (CODE_lift_track_45deg) | 45-deg (1:1) descending moving-platform rail. Shared init also serves $12; selector is $15 (object ID) bit 1, =0 here -> extent=2, slope step $17=$FFFF: rail drops 1 tile per column (measured 1 down / 1 right). Tables DATA_129396/DATA_12939A; keep-slope walker. $12 is the steeper 2:1 sibling.
!Define_YI_StdObj12_LiftTrack63Deg = $0012	; Init Bank12:2986 (CODE_init_lift_track_45deg); Stamp Bank13:992 | ~63-deg (2:1) descending moving-platform rail -- steeper than $11, NOT 45 degrees despite sharing the CODE_lift_track_45deg handler. Shared init reads $15 (object ID) bit 1 =1 here -> extent=3, slope step $17=$FFFE: rail drops 2 tiles per column (measured 2 down / 1 right = arctan 2 = 63.4 deg). $11 is the 1:1 (45-deg) sibling.
!Define_YI_StdObj13_LiftTrackStatic = $0013	; Init Bank12:3008 (CODE_init_lift_track_static); Stamp Bank13:1073 (CODE_lift_track_static) | Static horizontal lift rail. Trampoline-walker init.
!Define_YI_StdObj14_TunnelCut = $0014	; Init Bank12:3015 (CODE_init_tunnel); Stamp Bank13:1114 (CODE_tunnel_dispatch) | Tunnel cut into existing terrain: modifies the underlying tiles in a cutaway/cave-mouth fashion rather than drawing a fixed shape. Trampoline-walker init; stamp builds an adaptive box/column/row, picking sub-tiles by probing neighbours.
!Define_YI_StdObj15_CloudBlock = $0015	; Init Bank12:3022 (CODE_init_cloud_block); Stamp Bank13:1518 (CODE_cloud_block_stamp) | Cloud platform block. Forces row extent $2E=2 for the standard 2-row-tall cloud-block shape.
!Define_YI_StdObj16_WaterOpen = $0016	; Init Bank12:3031 (CODE_init_water_open); Stamp Bank13:1549 (CODE_water_open) | Open water. Stamper only writes the open-water tile into empty cells (doesn't overwrite pre-existing land).
!Define_YI_StdObj17_WaterMeetsGround = $0017	; Init Bank12:3038 (CODE_init_water_meets_ground); Stamp Bank13:1569 (CODE_water_meets_ground) | Water meets ground. Bumps row origin up by 1 (inline row-shift arithmetic) and increments extent so the waterline starts one row above the placed origin.
!Define_YI_StdObj18_WaterMeetsLand = $0018	; Init Bank12:3056 (CODE_init_water_meets_land_or_rock); Stamp Bank13:1705 (CODE_water_meets_land) | Water meets land variant. $15 bit 0 selects between water_meets_land and water_on_rock via DATA_129401/DATA_129403.
!Define_YI_StdObj19_WaterOnRock = $0019	; Init Bank12:3056 (CODE_init_water_meets_land_or_rock); Stamp Bank13:1757 (CODE_water_on_rock) | Water on rock variant. Shares handler with $18; $15 bit 0 picks this variant.
!Define_YI_StdObj1A_WaterBridgeHorizontal = $001A	; Init Bank12:3076 (CODE_init_water_bridge); Stamp Bank13:1808 (CODE_water_bridge_horizontal) | Water bridge (horizontal orientation). $15 bit 0 selects between horizontal/vertical via DATA_12941A/DATA_12941C.
!Define_YI_StdObj1B_WaterBridgeVertical = $001B	; Init Bank12:3076 (CODE_init_water_bridge); Stamp Bank13:1850 (CODE_water_bridge_vertical) | Water bridge (vertical orientation). Shares handler with $1A.
!Define_YI_StdObj1C_WaterLift = $001C	; Init Bank12:3096 (CODE_init_water_lift); Stamp Bank13:1900 (CODE_water_lift_stamp) | Under-water moving platform. Forces column extent $2A=2 for the standard 2-tile-wide bobbing-platform shape.
!Define_YI_StdObj1D_WaterDecorMushroom = $001D	; Init Bank12:3105 (CODE_init_water_decor); Stamp Bank13:1936 (CODE_water_decor_mushroom_flower) | Underwater mushroom decoration. Pointer-table DATA_129442/DATA_129444 has two identical entries -- the stamp body picks the orientation->tile mapping itself.
!Define_YI_StdObj1E_WaterDecorFlower = $001E	; Init Bank12:3105 (CODE_init_water_decor); Stamp Bank13:1936 | Underwater flower decoration. Shares handler with $1D.
!Define_YI_StdObj1F_WavyLava = $001F	; Init Bank12 CODE_init_lava_or_stone_3d; Stamp Bank13 CODE_lava_stamp | Wavy lava (castle levels; needs the correct level mode for the wave effect). Odd-id branch ($1F&1=1) of the shared lava/3D-stone init: builds a parity bit into $A1, writes a held-effect descriptor to $7F:7472+, then stamps via CODE_lava_stamp / CODE_lava_shared_segment. Companion to object $20 (3D stone).
!Define_YI_StdObj20_Stone3D = $0020	; Init Bank12 CODE_init_lava_or_stone_3d; Stamp Bank13 CODE_stone_3d_stamp | 3D stone (castle areas). Even-id branch ($20&1=0) of the shared lava/3D-stone init; stamps via CODE_stone_3d_stamp (the same shared 3D-stone stamp used by $EE/$EF and $F0-$F3). Companion to object $1F (wavy lava).
!Define_YI_StdObj21_JungleLedge = $0021	; Init Bank12:3231 (CODE_init_jungle_floor); Stamp Bank13:2020 (CODE_jungle_floor) | Muddy jungle ledge with grass. Zeroes $A1 (random-seed slot) before dispatch.
!Define_YI_StdObj22_JungleLeftWall = $0022	; Init Bank12:3239 (CODE_init_jungle_left_wall); Stamp Bank13:2223 (CODE_jungle_left_wall) | World 1 jungle left-edge wall. Increments $2A by 1 for the standard 1-extra-column-wide wall shape.
!Define_YI_StdObj23_JungleRightWall = $0023	; Init Bank12:3247 (CODE_init_jungle_right_wall); Stamp Bank13:2276 (CODE_jungle_right_wall) | Jungle right-edge wall. Bumps $2A to bias walker into vertical-down traversal.
!Define_YI_StdObj24_JungleMudLedge = $0024	; Init Bank12:3255 (CODE_init_jungle_mud_floor); Stamp Bank13:2354 (CODE_jungle_mud_floor) | Muddy jungle ledge (no grass). Plain walker setup; no orientation or random parameter writes.
!Define_YI_StdObj25_JungleMudWallLeft = $0025	; Init Bank12:3265 (CODE_init_jungle_mud_wall_lr); Stamp Bank13:2397 (CODE_jungle_mud_wall_left_right) | Jungle mud wall (left variant). Masks $15 bit 1 to select side, stores back, then dispatches via DATA_129518.
!Define_YI_StdObj26_JungleMudWallRight = $0026	; Init Bank12:3265 (CODE_init_jungle_mud_wall_lr); Stamp Bank13:2397 | Jungle mud wall (right variant). Shares handler with $25; $15 bit 1 picks this side.
!Define_YI_StdObj27_JungleSlope45LDRU = $0027	; Init Bank12:3279 (CODE_init_jungle_slope_45deg); Stamp Bank13:variant | Jungle 45-deg diagonal floor (left-down-right-up orientation). $15 bit 3 picks direction via DATA_12952E; presets $17=$FFFF; keep-slope walker.
!Define_YI_StdObj28_JungleSlope45LURD = $0028	; Init Bank12:3279 (CODE_init_jungle_slope_45deg); Stamp Bank13:variant | Jungle 45-deg diagonal floor (left-up-right-down orientation). Shares handler with $27; $15 bit 3 picks this direction.
!Define_YI_StdObj29_JungleTreetopCanopyLeft = $0029	; Init Bank12:3297 (CODE_init_jungle_treetop_canopy); Stamp Bank13:2704 (CODE_jungle_treetop_canopy) | Left half of a large jungle treetop canopy (leafy green foliage with hanging vines). $15 bit 1 = 0 selects the left-half tiles; init shifts the row origin up, $A1=0, $17=$0002 -- the canopy is built as an ascending tile run, so the old "StepsUp" name described the build mechanism, not the visual. Shared handler with $2A (right half) via DATA_12954B. [Identity confirmed by render + GoldenEgg.]
!Define_YI_StdObj2A_JungleTreetopCanopyRight = $002A	; Init Bank12:3297 (CODE_init_jungle_treetop_canopy); Stamp Bank13:2704 | Right half of a large jungle treetop canopy (mirror of $29). $15 bit 1 = 1 selects the right-half tiles. Shares handler with $29.
!Define_YI_StdObj2B_JungleStake = $002B	; Init Bank12:3312 (CODE_init_jungle_stake); Stamp Bank13:2755 (CODE_jungle_stake) | Jungle vertical stake / post. Stamp consumes caller-provided tile bases from WRAM $1DCE / $1DD4.
!Define_YI_StdObj2C_JungleStone = $002C	; Init Bank12:3319 (CODE_init_jungle_stone); Stamp Bank13:2791 (CODE_jungle_stone) | Jungle stone block. Bumps $2A (forces vertical-first walker traversal).
!Define_YI_StdObj2D_JungleVineThinA = $002D	; Init Bank12:3330 (CODE_init_jungle_vine_thin); Stamp Bank13:2843 (CODE_jungle_vine_thin) | Thin jungle vine variant A. PRNG bit 1 seeds $A1, bit 1 of $15 picks side; dispatches to CODE_jungle_vine_thin or CODE_jungle_vine_thin_plus_extras via DATA_12957F.
!Define_YI_StdObj2E_JungleVineThinB = $002E	; Init Bank12:3330 (CODE_init_jungle_vine_thin); Stamp Bank13:2923 (CODE_jungle_vine_thin_plus_extras) | Thin jungle vine variant B (with extras). Shares handler with $2D; $15 bit 1 picks this side.
!Define_YI_StdObj2F_JungleWood = $002F	; Init Bank12:3343 (CODE_init_jungle_wood); Stamp Bank13:2979 (CODE_jungle_wood) | Jungle wooden-log horizontal beam. Plain walker setup; no special state writes.
!Define_YI_StdObj30_JungleTreeTrunkPlain = $0030	; Init Bank12:3353 (CODE_init_jungle_tree_trunk); Stamp Bank13:variant | Jungle tree trunk (plain). PRNG bit 1 seeds $A1 (=$0B for leaf bias); bit 0 of $15 picks branches vs leaves variant via DATA_1295A6.
!Define_YI_StdObj31_JungleTreeTrunkLeaves = $0031	; Init Bank12:3353 (CODE_init_jungle_tree_trunk); Stamp Bank13:3146 (CODE_jungle_tree_trunk_with_leaves) | Jungle tree trunk (with leaves). Shares handler with $30; $15 bit 0 picks this variant.
!Define_YI_StdObj32_JungleBlockPatternA = $0032	; Init Bank12:3374 (CODE_init_jungle_block_pattern); Stamp Bank13:3236 (CODE_jungle_block_pattern_a) | Jungle patterned-block variant A. $15 bit 0 picks variant via DATA_1295CB; no other state writes.
!Define_YI_StdObj33_JungleBlockPatternB = $0033	; Init Bank12:3374 (CODE_init_jungle_block_pattern); Stamp Bank13:3402 (CODE_jungle_block_pattern_b) | Jungle patterned-block variant B. Shares handler with $32.
!Define_YI_StdObj34_JungleCattail = $0034	; Init Bank12:3385 (CODE_init_jungle_cattail); Stamp Bank13:3498 (CODE_jungle_cattail_random) | Jungle cattail (swampy reed-plant decoration); random variant. Bumps $2E (extent), zeroes $A1, PRNG-picks a variant, then dispatches.
!Define_YI_StdObj35_JungleWater = $0035	; Init Bank12:3394 (CODE_init_jungle_water); Stamp Bank13:3559 (CODE_jungle_water) | Jungle-tinted water surface. Zeroes $15 (orientation) before dispatch.
!Define_YI_StdObj36_JungleTreeLeavesOnly = $0036	; Init Bank12:3402 (CODE_init_jungle_tree_leaves_only); Stamp Bank13:3146 (CODE_jungle_tree_trunk_with_leaves) | Jungle tree variant: only the leafy crown. Sets $A1=$000B (leaf bias high) then dispatches; bypasses trunk-only path.
!Define_YI_StdObj37_RedPlatform = $0037	; Init Bank12:3411 (CODE_init_red_platform_tile); Stamp Bank13:3648 (CODE_stamp_red_platform_tile) | Red platform (static level-data tile; red-stairs visual style). Stamps tile $1512 only where the cell is empty, so it sits behind foreground tiles as a thin one-way platform. (Distinct from the red-platform sprite in Bank04.)
!Define_YI_StdObj38_StoneBlock = $0038	; Init Bank12 CODE_init_stone_large; Stamp Bank13 CODE_stamp_stone_large | Stone block (large castle stone, used in the Hookbill the Koopa boss room).
!Define_YI_StdObj39_StoneBlockRed = $0039	; Init Bank12 CODE_init_red_stone; Stamp Bank13 CODE_stamp_red_stone | Red stone block (small castle stone, Hookbill the Koopa boss room).
!Define_YI_StdObj3A_GrassSlope60DegUpHole = $003A	; Init Bank12:3443 (CODE_init_grass_slope_up_60deg_hole); Stamp Bank13:4214 (CODE_grass_slope_up_60deg_hole) | Grass-floor 60-deg upward slope with hole. Keep-slope walker.
!Define_YI_StdObj3B_GrassSlope60DegDownHole = $003B	; Init Bank12:3450 (CODE_init_grass_slope_down_60deg_hole); Stamp Bank13:4259 (CODE_grass_slope_down_60deg_hole) | Grass-floor 60-deg downward slope with hole. Computes $2E = $2E - 2*$2A (clamped >= 1); keep-slope walker.
!Define_YI_StdObj3C_PipeVerticalEnterable = $003C	; Init Bank12:3469 (CODE_init_pipe_vertical); Stamp Bank13:4312 (CODE_pipe_vertical_dispatch) | Enterable vertical pipe (Yoshi can enter; sizing $2A negative faces it downward). Masks $15 to bit 7 (orientation), sets $2A=$0002 (forces 2-column footprint). Shares init/dispatch with $F4 (the unenterable variant).
!Define_YI_StdObj3D_SnowCloudBlock = $003D	; Init Bank12:3481 (CODE_init_snow_cloud_block); Stamp Bank13:4368 (CODE_snow_cloud_block) | Snow-cloud platform / block. Sets $2E=$0003 (forces 3-row-tall footprint).
!Define_YI_StdObj3E_SkiLiftTwoPole = $003E	; Init Bank12:3490 (CODE_init_ski_lift_two_pole); Stamp Bank13:4435 (CODE_13A0E4) | Two ski-lift wire support poles side by side. Single-cell stamp that morphs the underlying tile to $00A7 / $00B3 / $00B4 based on the under-tile and row position.
!Define_YI_StdObj3F_SpikeLeft = $003F	; Init Bank12 CODE_init_spike_pillar; Stamp Bank13 CODE_stamp_spike_pillar | Left-facing spike (kills Yoshi instantly). Shares init/stamp with $40; uninstanced in playable levels.
!Define_YI_StdObj40_SpikeRight = $0040	; Init Bank12 CODE_init_spike_pillar; Stamp Bank13 CODE_stamp_spike_pillar | Right-facing spike (kills Yoshi instantly). See $3F.
!Define_YI_StdObj41_WallHBlock = $0041	; Init Bank12:3504 (CODE_init_wall_h_block); Stamp Bank13:4528 (CODE_wall_h_block) | Horizontal wall block. Stamps a horizontal-edge wall block with auto-connecting shadow/edge tiles on adjacent cells.
!Define_YI_StdObj42_CastlePillarTwoBlock = $0042	; Init Bank12:3515 (CODE_init_castle_pillar); Stamp Bank13:4758 (CODE_13A372) | Castle pillar, two block-tall segments (up-rise variant). Indexes DATA_1296AA by orientation bit 0 of $15.
!Define_YI_StdObj43_CastlePillar = $0043	; Init Bank12:3515 (CODE_init_castle_pillar); Stamp Bank13:4796 (CODE_13A3AF) | Castle pillar (down-fall variant). Shares handler with $42.
!Define_YI_StdObj44_CastleWall = $0044	; Init Bank12:3526 (CODE_init_castle_wall); Stamp Bank13:4856 (CODE_13A412) | Castle wall (corner-aware block). Autotile-state $A1=0. Stamps a corner-piece wall using shape probes of neighbouring cells.
!Define_YI_StdObj45_CastleWallDiagonalRight = $0045	; Init Bank12:3534 (CODE_init_castle_wall_diag_end); Stamp Bank13:5026 (CODE_13A553) | Downwards diagonal end of a castle wall, facing right (variant A). 2-column walker -- primary stamp CODE_13A553, secondary CODE_13A412, width 2, row origin up by 1, +/-1 column step from DATA_129712.
!Define_YI_StdObj46_CastleWallDiagonalLeft = $0046	; Init Bank12:3534 (CODE_init_castle_wall_diag_end); Stamp Bank13:5026 | Downwards diagonal end of a castle wall, facing left (mirror variant). Shares handler with $45.
!Define_YI_StdObj47_LavaCastle = $0047	; Init Bank12 CODE_init_lava_castle; Stamp Bank13 CODE_stamp_lava_castle | Lava (castle); kills Yoshi on contact. Stamper fills the rectangle with random tile variants from an 8-entry PRNG pool when the above-tile is not a continuation, plus neighbour autotile passes (varied lava surface).
!Define_YI_StdObj48_Brick = $0048	; Init Bank12:3581 (CODE_init_brick); Stamp Bank13:5318/5427 (CODE_13A753 + CODE_13A811) | Brick (castle brickwork block). Full walker setup with column stamp CODE_13A753 (top-edge handler) and per-row handler CODE_13A811 (body).
!Define_YI_StdObj49_CastleWallWindow = $0049	; Init Bank12:3600 (CODE_init_wall_block_thick_b); Stamp Bank13:5575 (CODE_13A90D) | Window in a castle wall (variant B, flavour 1). Width $2A=2.
!Define_YI_StdObj4A_CastlePillarSpiral = $004A	; Init Bank12:3600 (CODE_init_wall_block_thick_b); Stamp Bank13:5575 | Castle pillar with spiral decoration (variant B, flavour 2). Shares handler with $49.
!Define_YI_StdObj4B_CheckeredBlock4 = $004B	; Init Bank12:3620 (CODE_init_wall_column_variable); Stamp Bank13:5609 (CODE_13A94B) | Checkered block, width 4 tiles (3-skin column). Reads $15 bits 0-2, decrements 3x to derive index, then DATA_129797 picks column width.
!Define_YI_StdObj4C_CheckeredBlock6 = $004C	; Init Bank12:3620 (CODE_init_wall_column_variable); Stamp Bank13:5609 | Checkered block, width 6 tiles (3-skin column). Shares handler with $4B/$4D.
!Define_YI_StdObj4D_CheckeredBlock8 = $004D	; Init Bank12:3620 (CODE_init_wall_column_variable); Stamp Bank13:5609 | Checkered block, width 8 tiles (3-skin column). Shares handler with $4B/$4C.
!Define_YI_StdObj4E_SandBlock = $004E	; Init Bank12:3651 (CODE_init_bg_autotile_block); Stamp Bank13:5671 (CODE_13A9F6) | Sand block: neighbour-aware autotiling ground block (appears as sand in the relevant tilesets), used widely across levels.
!Define_YI_StdObj4F_SandBlockRemover = $004F	; Init Bank12:3669 (CODE_init_bg_autotile_decor_lookup); Stamp Bank13:6299 (CODE_13B13F) | Sand block remover: decorative tile-pack with 188-entry lookup. 4-direction neighbour probe + self-replacement against the curated decoration LUT.
!Define_YI_StdObj50_GraffitiRailV = $0050	; Init Bank12:3687 (CODE_init_graffiti_rail); Stamp Bank13:6505 (CODE_13B924) | Vertical graffiti rail (decorative). Stamper picks tile from a 2-entry table with overrides for special-zone tiles.
!Define_YI_StdObj51_GraffitiRailH = $0051	; Init Bank12:3687 (CODE_init_graffiti_rail); Stamp Bank13:6505 | Horizontal graffiti rail. Shares handler with $50.
!Define_YI_StdObj52_GraffitiRailD = $0052	; Init Bank12:3705 (CODE_init_graffiti_rail_diagonal); Stamp Bank13:6539 (CODE_13B95C) | Diagonal graffiti rail. $17=$FFFF (left-stepping per-row slope) for the diagonal shape.
!Define_YI_StdObj53_CastleWallPlatformH = $0053	; Init Bank12:3724 (CODE_init_castle_wall_platform); Stamp Bank13:6568 (CODE_13B98D) | Horizontal platform on a castle wall. Sets up the autotile stamp pattern in a single rectangle (broad neighbour-class lookup).
!Define_YI_StdObj54_CastleWallPlatformDownSlow = $0054	; Init Bank12:3731 (CODE_init_castle_wall_platform_slope); Stamp Bank13:6646 (CODE_13BA20) | Gradually downward-slanted platform on a castle wall. Per-row slope $17 from DATA_129854 ($FFFF/$FFFF/$FFFE) per orientation $15 bits 0-1.
!Define_YI_StdObj55_CastleWallPlatformDown = $0055	; Init Bank12:3731 (CODE_init_castle_wall_platform_slope); Stamp Bank13:6646 | Downward-slanted platform on a castle wall (medium). Shares handler with $54/$56.
!Define_YI_StdObj56_CastleWallPlatformDownSteep = $0056	; Init Bank12:3731 (CODE_init_castle_wall_platform_slope); Stamp Bank13:6646 | Steeply downward-slanted platform on a castle wall. Shares handler with $54/$55.
!Define_YI_StdObj57_TunnelPlatform = $0057	; Init Bank12:3758 (CODE_init_seven_segment_decor); Stamp Bank13:6819 (CODE_13BB45) | Platform in a tunnel cutaway view (7-segment decorative band). Shared with $7E -- the two non-adjacent IDs both route here via DATA_standard_object_init_ptrs.
!Define_YI_StdObj58_LedgeBottomCeiling = $0058	; Init Bank12:3776 (CODE_init_thick_post_overlay); Stamp Bank13:6873 (CODE_13BBA6) | Ceiling of a ledge; attaching it to solid ground connects it with a ledge edge.
!Define_YI_StdObj59_TunnelBottomDownRightGradual = $0059	; Init Bank12:3795 (CODE_init_tunnel_floor_slope_right); Stamp Bank13:DATA_1298E9 | Tunnel floor sloping down-right (gradual); 3-variant family. Stamp from DATA_1298E9 picked by $15 bits 0-1; slope $17 from DATA_1298EF ($FFFF/$FFFF/$FFFE). Shifts row origin up by 1.
!Define_YI_StdObj5A_TunnelBottomDownRight = $005A	; Init Bank12:3795 (CODE_init_tunnel_floor_slope_right); Stamp Bank13:DATA_1298E9 | Tunnel floor sloping down-right (medium). Shares handler with $59/$5B.
!Define_YI_StdObj5B_TunnelBottomDownRightSteep = $005B	; Init Bank12:3795 (CODE_init_tunnel_floor_slope_right); Stamp Bank13:DATA_1298E9 | Tunnel floor sloping down-right (steep). Shares handler with $59/$5A.
!Define_YI_StdObj5C_TunnelBottomDownLeftGradual = $005C	; Init Bank12:3844 (CODE_init_tunnel_floor_slope_left); Stamp Bank13:DATA_1298E9 | Tunnel floor sloping down-left (gradual); parallel 3-variant family. Same DATA_1298E9 stamp pointers but uses DATA_129938 ($0001,$0001,$0002) for $17 (positive step).
!Define_YI_StdObj5D_TunnelBottomDownLeft = $005D	; Init Bank12:3844 (CODE_init_tunnel_floor_slope_left); Stamp Bank13:DATA_1298E9 | Tunnel floor sloping down-left (medium). Shares handler with $5C/$5E.
!Define_YI_StdObj5E_TunnelBottomDownLeftSteep = $005E	; Init Bank12:3844 (CODE_init_tunnel_floor_slope_left); Stamp Bank13:DATA_1298E9 | Tunnel floor sloping down-left (steep). Shares handler with $5C/$5D.
!Define_YI_StdObj5F_TunnelTopUpRightGradual = $005F	; Init Bank12:3884 (CODE_init_tunnel_ceiling_slope_right); Stamp Bank13:7323 (CODE_13BEF5) | Tunnel ceiling sloping up-right (gradual). Computes $2E from $15 bits 0-3 halved if set; clamps; INCs $2A/$2E by 2; clears $A1.
!Define_YI_StdObj60_TunnelTopUpRight = $0060	; Init Bank12:3884 (CODE_init_tunnel_ceiling_slope_right); Stamp Bank13:7323 | Tunnel ceiling sloping up-right (medium). Shares handler with $5F.
!Define_YI_StdObj61_TunnelTopUpLeftGradual = $0061	; Init Bank12:3928 (CODE_init_tunnel_ceiling_slope_left); Stamp Bank13:7489 (CODE_tunnel_ceiling_slope_left) | Tunnel ceiling sloping up-left (gradual). Picks extents from $15 bit 1 + $2A/$2E, shifts row origin up.
!Define_YI_StdObj62_TunnelTopUpLeft = $0062	; Init Bank12:3928 (CODE_init_tunnel_ceiling_slope_left); Stamp Bank13:7489 | Tunnel ceiling sloping up-left (medium). Shares handler with $61.
!Define_YI_StdObj63_BrownPlatform = $0063	; Init Bank12:3999 (CODE_init_three_segment_row); Stamp Bank13:7710 (CODE_three_segment_row) | Horizontal brown platform (variant A). Stamp picks $151E left / $151F middle / $1520 right by column position.
!Define_YI_StdObj64_BrownPlatformB = $0064	; Init Bank12:3999 (CODE_init_three_segment_row); Stamp Bank13:7710 | Horizontal brown platform (variant B). Shares handler with $63/$65.
!Define_YI_StdObj65_BrownPlatformC = $0065	; Init Bank12:3999 (CODE_init_three_segment_row); Stamp Bank13:7710 | Horizontal brown platform (variant C). Shares handler with $63/$64.
!Define_YI_StdObj66_IceBlockMeltable = $0066	; Init Bank12:4017 (CODE_init_2x2_repeating_block); Stamp Bank13:7730 (CODE_2x2_repeating_block) | Meltable ice block (2x2 repeating tile pattern). Picks 1 of 4 tiles $8900-$8903 from col-parity | row-parity<<1.
!Define_YI_StdObj67_Ground = $0067	; Init Bank12:4035 (CODE_init_big_floor_or_jungle_canopy); Stamp Bank13:7746/8075 | Ground (general floor); tileset-conditional. If BG1 tileset == $0C (jungle), uses CODE_jungle_canopy_random (CODE_13C6A5). Otherwise CODE_big_floor_stamp (CODE_13C2AF) -- base + 8 edge fix-ups.
!Define_YI_StdObj68_Coin = $0068	; Init Bank12 CODE_init_coin_object; Stamp Bank13 CODE_stamp_coin | Coin (affects item memory). Stamp picks the present/collected tile ($6000 vs $7400) from $15 bit 1, gated by a CODE_01E501 item-memory probe. Shares init/stamp with $8A (the !-switch coin).
!Define_YI_StdObj69_SinkingFloor = $0069	; Init Bank12:4059 (CODE_init_3x3_structural); Stamp Bank13:8113 (CODE_3x3_structural) | Sinking floor (3-column structural block). Clamps $2A and $2E to a minimum of 4.
!Define_YI_StdObj6A_3WidePlatformUnused = $006A	; Init Bank12:4078 (CODE_init_3wide_platform_bar); Stamp Bank13:8162 (CODE_3wide_platform_bar) | 3-wide horizontal platform bar (unused; small lift body). Picks $6400/$6401/$6402 by column position.
!Define_YI_StdObj6B_GoalPlatform = $006B	; Init Bank12:4085 (CODE_init_goal_platform); Stamp Bank13:8180 (CODE_goal_platform) | Goal platform. Wide structure with neighbour-probe edge-snap. INCs $2E, shifts column origin left by $10.
!Define_YI_StdObj6C_GrayCementBlock = $006C	; Init Bank12:4103 (CODE_init_gray_cement_block); Stamp Bank13:8247 (CODE_gray_cement_block) | Gray cement block. Stamps constant tile $0184 then JMPs CODE_13A833 to attach a secondary effect.
!Define_YI_StdObj6D_SpikyStake = $006D	; Init Bank12 CODE_init_spiky_stake; Stamp Bank13 CODE_stamp_spiky_stake | Spiky stake (a stake sharpened to a spike; hurts Yoshi on contact).
!Define_YI_StdObj6E_ColorfulCementBlock = $006E	; Init Bank12:4117 (CODE_init_random_decoration_8way); Stamp Bank13:8281 (CODE_random_decoration_8way) | Colorful cement block. Randomised 8-way decoration scatter: PRNG-picks 1 of 8 tiles $0199-$01A0. Shared with $8B (which overrides to $7300).
!Define_YI_StdObj6F_TwistedTreeTrunk = $006F	; Init Bank12 CODE_init_twisted_tree_trunk; Stamp Bank13 CODE_stamp_twisted_tree_trunk | Twisted tree trunk (forest decoration; the trunk that $73-$78 leaves attach to).
!Define_YI_StdObj70_ForestPlants = $0070	; Init Bank12 CODE_init_forest_plants; Stamp Bank13 CODE_stamp_forest_plants | Plants on the forest ground (2x2 decoration).
!Define_YI_StdObj71_ForestFlowerAbove = $0071	; Init Bank12 CODE_init_forest_flower_above; Stamp Bank13 CODE_stamp_forest_flower_above | Large flowers on the forest ground (2x2 decoration).
!Define_YI_StdObj72_ForestFlowerBelow = $0072	; Init Bank12 CODE_init_forest_flower_below; Stamp Bank13 CODE_stamp_forest_flower_below | Large flowers beneath the forest ground (2x2 decoration).
!Define_YI_StdObj73_TwistedTreeLeaves = $0073	; Init Bank12 CODE_init_twisted_tree_leaves; Stamp Bank13 CODE_stamp_twisted_tree_leaves | Leaves on a twisted tree (3x2 decoration).
!Define_YI_StdObj74_TwistedTreeLeavesWide = $0074	; Init Bank12 CODE_init_twisted_tree_leaves_wide; Stamp Bank13 CODE_stamp_twisted_tree_leaves_wide | Leaves on a twisted tree (3-wide decoration).
!Define_YI_StdObj75_TwistedTreeLeafLeft = $0075	; Init Bank12 CODE_init_twisted_tree_leaf_left; Stamp Bank13 CODE_stamp_twisted_tree_leaf_left | Left-facing leaves on a twisted tree.
!Define_YI_StdObj76_TwistedTreeLeafRight = $0076	; Init Bank12 CODE_init_twisted_tree_leaf_right; Stamp Bank13 CODE_stamp_twisted_tree_leaf_right | Right-facing leaves on a twisted tree.
!Define_YI_StdObj77_TwistedTreeLeafCenter = $0077	; Init Bank12 CODE_init_twisted_tree_leaf_center; Stamp Bank13 CODE_stamp_twisted_tree_leaf_center | Center leaves on a twisted tree.
!Define_YI_StdObj78_TwistedTreeSlanted = $0078	; Init Bank12 CODE_init_twisted_tree_slanted; Stamp Bank13 CODE_stamp_twisted_tree_slanted | Slanted twisted tree (size negative = grows left).
!Define_YI_StdObj79_RedStairs = $0079	; Init Bank12:4242 (CODE_init_red_stairs); Stamp Bank13:8506 (CODE_red_stairs_stamp) | Red stairs, 2-row tall. Force $2E=2. Loads DATA_13C961 4-entry tile table; row,col pick interior vs left-cap.
!Define_YI_StdObj7A_Wall = $007A	; Init Bank12:4263 (CODE_init_smart_floor_junction); Stamp Bank13:8568 (CODE_smart_floor_junction_stamp) | Wall (smart floor/wall/corner auto-pick). 9-handler dispatch (DATA_13C9ED) indexed by (col-class, row-class); per-neighbour probing picks Map16 edge/corner template.
!Define_YI_StdObj7B_WallDiagonal = $007B	; Init Bank12:4270 (CODE_init_floor_slope_curve); Stamp Bank13:8816 (CODE_floor_slope_curve_stamp) | Diagonal wall. Keep-slope walker with $17=$FFFF; stamp picks descending vs ascending sub-handler from sign of $2A.
!Define_YI_StdObj7C_WallCeilingDiagonal = $007C	; Init Bank12:4279 (CODE_init_slope_decoration_dual); Stamp Bank13:9018 (CODE_slope_decoration_dual_stamp) | Upside-down (ceiling) diagonal wall. Takes abs($2A) into $2E (so width is always positive); right-edge skip and end-of-row probe of $1D92/$1D98/$1D8A ceiling markers.
!Define_YI_StdObj7D_WallLedgeOverhang = $007D	; Init Bank12:4292 (CODE_init_overhang_2row); Stamp Bank13:9086 (CODE_overhang_2row_stamp) | Ledge / overhang found on a wall.
!Define_YI_StdObj7E_WallPlatform = $007E	; Init Bank12:3758 (CODE_init_seven_segment_decor); Stamp Bank13:6819 (CODE_13BB45) | Platform on a wall (7-segment decorative band) -- shared handler with $57 (non-adjacent ID alias). Both IDs route to the same init via DATA_standard_object_init_ptrs.
!Define_YI_StdObj7F_WallHole = $007F	; Init Bank12:4301 (CODE_init_decoration_min2x2); Stamp Bank13:9152 (CODE_decoration_min2x2_stamp) | Wall hole: tall multi-tile decoration (min 2x2). Forces both $2A and $2E to at least 2; short-circuits cells where $12=0; on $1D8A-row indexes 9 sub-tables in DATA_13CE34 by (col,row).

!Define_YI_StdObj80_WallCeilingDiagonalSignedFill = $0080	; Init Bank12:4319; Stamp Bank13:9324 | Upside-down (ceiling) diagonal wall, signed-direction fill. Init takes abs($2A) into $2E so caller can encode signed direction in $2A. CODE_init_slope_fill_signed -> CODE_13D01A.
!Define_YI_StdObj81_WallDiagonalSignedFill = $0081	; Init Bank12:4332; Stamp Bank13:9411 | Diagonal wall, wide signed-direction fill (keep-slope mode, $19=$7FFF max width, $17=$FFFF descending). CODE_init_wide_slope_signed -> CODE_13D098.
!Define_YI_StdObj82_GreenCoin = $0082	; Init Bank12:4357; Stamp Bank13:9465 | Green coin collectible; stamps $A400 (item-memory-tracked coin tile) only into unclaimed cells. Std-object twin of ext-object $17. Shared init for $82/$83. CODE_init_special_coin -> CODE_13D0E6.
!Define_YI_StdObj83_GreenCoinHorizontal = $0083	; Init Bank12:4357; Stamp Bank13:9465 | Green coin collectible, placed every 2 blocks (same init as $82). Duplicate dispatch entry; behaviour identical.
!Define_YI_StdObj84_GreenCoinDiagonal = $0084	; Init Bank12:4364; Stamp Bank13:9485 | Green coin collectible, keep-slope/diagonal variant placed every 2 blocks ($17=$FFFF). CODE_init_special_coin_keepslope -> CODE_13D10A.
!Define_YI_StdObj85_TunnelTopUpRightSteep = $0085	; Init Bank12:4373; Stamp Bank13:9507 | Tunnel ceiling sloping up-right (steep); horizontal ceiling row with right-neighbour endcap detection. CODE_init_tunnel_ceiling_slope_right_steep -> CODE_13D130.
!Define_YI_StdObj86_TunnelTopUpLeftSteep = $0086	; Init Bank12:4380; Stamp Bank13:9579 | Tunnel ceiling sloping up-left (steep); vertical wall column with endcap. Init computes $2E-$2A delta into $2E so height shrinks by initial column index. CODE_init_tunnel_ceiling_slope_left_steep -> CODE_13D1B0.
!Define_YI_StdObj87_FloorNoDecoTop = $0087	; Init Bank12 CODE_init_floor_no_deco_top; Stamp Bank13 CODE_stamp_floor_no_deco_top | Floor without top decoration. Walker uses CODE_bg_floor_random as the random-fill bank. Shares init/stamp with $88.
!Define_YI_StdObj88_LedgeNoGrassUniform = $0088	; Init Bank12 CODE_init_floor_no_deco_top; Stamp Bank13 CODE_stamp_floor_no_deco_top | Ledge without grass; more uniform in style than object $87.
!Define_YI_StdObj89_FallingRock = $0089	; Init Bank12 CODE_init_falling_rock; Stamp Bank13 CODE_stamp_falling_rock | Falling rock (a large rock that falls after Yoshi lands on it).
!Define_YI_StdObj8A_SwitchCoin = $008A	; Init Bank12 CODE_init_coin_object; Stamp Bank13 CODE_stamp_coin | !-switch coin (collectible only while a !-switch is active; affects item memory). Stores stamp bank in $039E; same init/stamp as $68.
!Define_YI_StdObj8B_SwitchBlock = $008B	; | !-switch block (only solid while a !-switch is active). Shares a PRNG 8-tile-scatter init/stamp with $6E (colorful cement block), so that handler keeps a generic name.
!Define_YI_StdObj8C_BooGuyBombRoom = $008C	; Init Bank12 CODE_init_boo_guy_bomb_room; Stamp Bank13 CODE_stamp_boo_guy_bomb_room | Boo Guy bomb-brigade room (the room where Boo Guys line up to drop bombs on Yoshi).
!Define_YI_StdObj8D_Tree = $008D	; Init Bank12:4434; Stamp Bank13:9915 | Tree (single-row decoration). CODE_init_tree -> CODE_13D3ED.
!Define_YI_StdObj8E_DonutBlockLarge = $008E	; Init Bank12 CODE_init_donut_lift_giant; Stamp Bank13 CODE_stamp_donut_lift_giant | Large donut block (2x2; falls if Yoshi stands on it too long).
!Define_YI_StdObj8F_SlantedLogGradual = $008F	; Init Bank12:4454; Stamp Bank13:9982 | Slanted log stuck in the ground (gradual). Full walker setup with $19=$7FFF $17=$FFFF. CODE_init_slanted_log_gradual -> CODE_13D473.
!Define_YI_StdObj90_SlantedLog = $0090	; Init Bank12:4473; Stamp Bank13:10146 | Slanted log stuck in the ground (mirror direction; $19=$7FFF $17=$FFFF). CODE_init_slanted_log -> CODE_13D574.
!Define_YI_StdObj91_TreeWithSporeLeft = $0091	; Init Bank12:4496; Stamp Bank13:10246 | Tree with spore (3-wide tree-cap), left variant. Init forces $2A=3, shifts col origin left by 1, then $15 bit 1 picks variant A (CODE_13D61A) or B (CODE_13D675) via DATA_treecap_variant_handlers. Shared with $92. CODE_init_treecap_3wide.
!Define_YI_StdObj92_TreeWithSporeRight = $0092	; Init Bank12:4496; Stamp Bank13:10246 | Tree with spore (3-wide tree-cap), right variant (duplicate dispatch of $91, variant via $15 bit 1).
!Define_YI_StdObj93_PalmTree = $0093	; Init Bank12:4518; Stamp Bank13:10347 | Palm tree (4-wide tree-cap). Init forces $2A=4, shifts col origin left by 1. CODE_init_treecap_4wide -> CODE_13D6D2.
!Define_YI_StdObj94_NumberPlatform1 = $0094	; Init Bank12 CODE_init_number_platform; Stamp Bank13 CODE_stamp_number_platform | Number platform 1 (vanishes after Yoshi gets off it). Shares init/stamp with $95-$97 (the number is keyed on object id).
!Define_YI_StdObj95_NumberPlatform2 = $0095	; Init Bank12 CODE_init_number_platform; Stamp Bank13 CODE_stamp_number_platform | Number platform 2 (turns into $94 after Yoshi gets off). See $94.
!Define_YI_StdObj96_NumberPlatform3 = $0096	; Init Bank12 CODE_init_number_platform; Stamp Bank13 CODE_stamp_number_platform | Number platform 3 (turns into $95 after Yoshi gets off). See $94.
!Define_YI_StdObj97_NumberPlatform4 = $0097	; Init Bank12 CODE_init_number_platform; Stamp Bank13 CODE_stamp_number_platform | Number platform 4 (turns into $96 after Yoshi gets off). See $94.
!Define_YI_StdObj98_Waterfall = $0098	; Init Bank12:4552; Stamp Bank13:10429 | Waterfall (3-segment vertical column). Stamp sub-dispatches on $2C row-position (top/middle/base) into 3 tile-set pickers. CODE_init_column_3segment -> CODE_13D76B.
!Define_YI_StdObj99_RockInWaterfall = $0099	; Init Bank12:4559; Stamp Bank13:10503 | Rock in a waterfall (3-wide floor block, random middle column). Init forces $2A=3, shifts row origin left by 1 nibble. Middle column JSLs CODE_bg_floor_random. CODE_init_rock_in_waterfall -> CODE_13D7DE.
!Define_YI_StdObj9A_PlantCaveLarge = $009A	; Init Bank12:4578; Stamp Bank13:10560 | Large cave plant (4-wide PRNG-decorated floor). Init forces $2A=4, shifts row origin left by 2 nibbles, PRNG-picks $15 (variant 0-3) and $A1 (mirror). CODE_init_plant_cave_large -> CODE_13D855.
!Define_YI_StdObj9B_PlantCaveSmall = $009B	; Init Bank12:4608; Stamp Bank13:10723/10808 | Small cave plant (random-decorated, orientation 0). $15 bit 2 picks body via DATA_ledge_random_body_ptrs: CODE_13D945 or CODE_13D9C8. PRNG sets $15 + $A1 like $9A. Shared with $9C. CODE_init_ledge_random_variant.
!Define_YI_StdObj9C_PlantCave = $009C	; Init Bank12:4608; Stamp Bank13:10723/10808 | Cave plant (random-decorated, orientation 1, same init). See $9B.
!Define_YI_StdObj9D_StationaryRock = $009D	; Init Bank12 CODE_init_stationary_rock; Stamp Bank13 CODE_stamp_stationary_rock | Stationary rock (a large rock that does NOT fall when Yoshi lands on it; cf. $89 FallingRock).
!Define_YI_StdObj9E_DonutBlock = $009E	; Init Bank12 CODE_init_donut_lift; Stamp Bank13 CODE_stamp_donut_lift | Donut block (single-tile; falls if Yoshi stands on it too long).
!Define_YI_StdObj9F_RavenPlatform = $009F	; Init Bank12:4639; Stamp Bank13:10954 | Raven's platform (2-row raised step). Forces $2E=2 and rounds $2A up to even. Stamp reads 4-entry DATA_13DA9C ($3308/$3508/$0004/$0005). CODE_init_raven_platform -> CODE_13DAA4.
!Define_YI_StdObjA0_RedBlock = $00A0	; Init Bank12:4652; Stamp Bank13:10980 | Red block (variant 0). Masks $15 & $000F, ASLs as per-variant tile offset. Rounds $2A up to even. Shared with $A1-$A2. CODE_init_colored_block -> CODE_13DACC.
!Define_YI_StdObjA1_YellowBlock = $00A1	; Init Bank12:4652; Stamp Bank13:10980 | Yellow block (variant 1). Shares handler with $A0/$A2.
!Define_YI_StdObjA2_GreenBlock = $00A2	; Init Bank12:4652; Stamp Bank13:10980 | Green block (variant 2). Shares handler with $A0/$A1.
!Define_YI_StdObjA3_BreakableRock = $00A3	; Init Bank12:4667; Stamp Bank13:10999 | Breakable rock (2x2 block, variant 0 by $15 bit 2). Forces $15=bit-2, rounds $2A and $2E up to even. Shared with $A4. CODE_init_breakable_rock -> CODE_13DAEC.
!Define_YI_StdObjA4_BreakableRockCracked = $00A4	; Init Bank12:4667; Stamp Bank13:10999 | Breakable rock, cracked/fragile (2x2 block, variant 1, same init). See $A3.
!Define_YI_StdObjA5_PipeDoubleEndedVertical = $00A5	; Init Bank12:4689; Stamp Bank13:varies | Double-ended vertical pipe (orientation pair 0). If BG1 tileset==$03 overrides $2A or $2E to $0002 from DATA_pipe_extent_override. Trampolines into CODE_pipe_dispatch (shared 4-orientation pipe stamper in same bank). Shared with $A6. CODE_init_pipe.
!Define_YI_StdObjA6_PipeDoubleEndedHorizontal = $00A6	; Init Bank12:4689; Stamp Bank13:varies | Double-ended horizontal pipe (orientation pair 1, same init via $15 bit 1).
!Define_YI_StdObjA7_SpikeBallArea = $00A7	; Init Bank12 CODE_129EDE; Stamp Bank13 $11285/$11342 | Spike-ball area / group of thorns (kills Yoshi instantly). Shares a corner-aware 2-variant init/stamp (CODE_129EDE) with $A8 (the blank/eraser variant), so that handler keeps a generic name.
!Define_YI_StdObjA8_SpikeBallAreaEraser = $00A8	; Init Bank12:4716; Stamp Bank13:11285/11342 | Spike-ball-area eraser (blank-tile variant 1; clears within a spike-ball area). Shares handler with $A7.
!Define_YI_StdObjA9_ChompSignPostOrVerticalPipe = $00A9	; Init Bank12:4745; Stamp Bank13:11460/11484 | Chomp sign-post prop, or vertical pipe (tileset-conditional): if BG1 tileset==$03 forces $2A=2 + uses CODE_stamp_water_top_3state (CODE_13DDF0); else uses CODE_stamp_cliff_top (CODE_13DDCA). CODE_init_chomp_sign_or_pipe.
!Define_YI_StdObjAA_SewagePipeEdgeVerticalEdgeLeft = $00AA	; Init Bank12:4766; Stamp Bank13:11641/11681 | Vertical sewage-pipe edge, left (orientation 0). Forces $2A=2. $15 bit 0 picks body via DATA_wall_vertical_body_ptrs: CODE_stamp_wall_vleft (CODE_13DF04) or CODE_stamp_wall_vright (CODE_13DF50). Both bodies run template-aware tile remap. Shared with $AB. CODE_init_wall_vertical_pair.
!Define_YI_StdObjAB_SewagePipeEdgeVerticalEdgeRight = $00AB	; Init Bank12:4766; Stamp Bank13:11641/11681 | Vertical sewage-pipe edge, right (orientation 1).
!Define_YI_StdObjAC_SewagePipeEdgeHorizontalCeiling = $00AC	; Init Bank12:4783; Stamp Bank13:11555/11601 | Horizontal sewage-pipe edge, ceiling (orientation 0). If BG1 tileset==$0B forces $2E=2. $15 bit 0 picks body via DATA_wall_horizontal_body_ptrs: CODE_stamp_wall_htop (CODE_13DE61) or CODE_stamp_wall_hbottom (CODE_13DEB8). Shared with $AD. CODE_init_wall_horizontal_pair.
!Define_YI_StdObjAD_SewagePipeEdgeHorizontalFloor = $00AD	; Init Bank12:4783; Stamp Bank13:11555/11601 | Horizontal sewage-pipe edge, floor (orientation 1).
!Define_YI_StdObjAE_SewagePipeWallVertical = $00AE	; Init Bank12:4804; Stamp Bank13:11819/11842 | Sewage-pipe wall, vertical (orientation 0). $15 bit 0 selects which of $2A/$2E becomes 2 AND which body via DATA_decoration_2tile_body_ptrs: CODE_stamp_dec_2tile_vert (CODE_13E148) or CODE_stamp_dec_2tile_horiz (CODE_13E170). Shared with $AF. CODE_init_decoration_2tile_pair.
!Define_YI_StdObjAF_SewagePipeWallHorizontal = $00AF	; Init Bank12:4804; Stamp Bank13:11819/11842 | Sewage-pipe wall, horizontal (orientation 1).
!Define_YI_StdObjB0_SewagePipeWall = $00B0	; Init Bank12:4822; Stamp Bank13:11866 | Sewage-pipe wall (corner-aware 4x4 block) ($77 page). Stamp uses 16-entry DATA_13E190 indexed by 5-bucket corner position. CODE_init_decoration_corner_block -> CODE_13E1B0.
!Define_YI_StdObjB1_SewagePipeWallPlatform = $00B1	; Init Bank12:4829; Stamp Bank13:11928 | Platform on a sewage-pipe wall (current-tile-aware remap). Stamp matches $12 against DATA_13E1FE and writes a tileset-correct replacement. CODE_init_decoration_tile_remap -> CODE_13E246.
!Define_YI_StdObjB2_SewagePipeEdgeDiagonalCeilingLeft = $00B2	; Init Bank12:5002; Stamp Bank13:12238 | Diagonal sewage pipe, 3-row, orientation A, ceiling edge. $2E=3, $17=$FFFF, KEEP-SLOPE walker; CODE_init_diagonal_sewage_pipe_3row picks ceiling stamp CODE_stamp_diagonal_sewage_pipe_ceiling ($15 bit 0 = 0). Pairs with floor $B3. Uninstanced in retail levels.
!Define_YI_StdObjB3_SewagePipeEdgeDiagonalFloorLeft = $00B3	; Init Bank12:5002; Stamp Bank13:12260 | Diagonal sewage pipe, 3-row, orientation A, floor edge ($15 bit 0 = 1 -> CODE_stamp_diagonal_sewage_pipe_3row_floor).
!Define_YI_StdObjB4_SewagePipeEdgeLargeDiagonalCeilingLeft = $00B4	; Init Bank12:5021; Stamp Bank13:12238 | Diagonal sewage pipe, 4-row ("large"), orientation A, ceiling edge. Same as $B2 but $2E=4; shares ceiling stamp CODE_stamp_diagonal_sewage_pipe_ceiling with $B2. Pairs with floor $B5.
!Define_YI_StdObjB5_SewagePipeEdgeLargeDiagonalFloorLeft = $00B5	; Init Bank12:5021; Stamp Bank13:12281 | Diagonal sewage pipe, 4-row, orientation A, floor edge (CODE_stamp_diagonal_sewage_pipe_4row_floor).
!Define_YI_StdObjB6_SewagePipeEdgeDiagonalCeilingRight = $00B6	; Init Bank12:5040; Stamp Bank13:12302 | Diagonal sewage pipe, 3-row, orientation B, ceiling edge. $2E=3, $17=$FFFF, KEEP-SLOPE walker; CODE_init_diagonal_sewage_pipe_3row_alt picks ceiling stamp CODE_stamp_diagonal_sewage_pipe_alt_ceiling ($15 bit 0 = 0), which probes the map16 below for shape continuation. Pairs with floor $B7.
!Define_YI_StdObjB7_SewagePipeEdgeDiagonalFloorRight = $00B7	; Init Bank12:5040; Stamp Bank13:12339 | Diagonal sewage pipe, 3-row, orientation B, floor edge (CODE_stamp_diagonal_sewage_pipe_3row_alt_floor; probes map16 above).
!Define_YI_StdObjB8_SewagePipeEdgeLargeDiagonalCeilingRight = $00B8	; Init Bank12:5059; Stamp Bank13:12302 | Diagonal sewage pipe, 4-row ("large"), orientation B, ceiling edge. The 4-row sibling of $B6 (as $B4 is to $B2): $2E=4; shares ceiling stamp CODE_stamp_diagonal_sewage_pipe_alt_ceiling with $B6. Pairs with floor $B9.
!Define_YI_StdObjB9_SewagePipeEdgeLargeDiagonalFloorRight = $00B9	; Init Bank12:5059; Stamp Bank13:12376 | Diagonal sewage pipe, 4-row, orientation B, floor edge (CODE_stamp_diagonal_sewage_pipe_4row_alt_floor; probes map16 above).
!Define_YI_StdObjBA_SewagePipeEdgeDeadEndTop = $00BA	; Init Bank12:4916; Stamp Bank13:varies | Sewage-pipe dead end, top (variant 0 of 4). Picks 1 of 4 stamps from DATA_pipe_entrance_stamps via ($15-2)&3: CODE_13E3BB / CODE_13E3EA / CODE_13E448 / CODE_13E419. Walker_setup_trampoline. Shared with $BB-$BD. CODE_init_pipe_entrance.
!Define_YI_StdObjBB_SewagePipeEdgeDeadEndBottom = $00BB	; Init Bank12:4916; Stamp Bank13:varies | Sewage-pipe dead end, bottom (variant 1).
!Define_YI_StdObjBC_SewagePipeEdgeDeadEndRight = $00BC	; Init Bank12:4916; Stamp Bank13:varies | Sewage-pipe dead end, right (variant 2).
!Define_YI_StdObjBD_SewagePipeEdgeDeadEndLeft = $00BD	; Init Bank12:4916; Stamp Bank13:varies | Sewage-pipe dead end, left (variant 3). Note: leveldataengine.md §4 categorised $BD as vestigial; in V1.0 it is a live 4-variant slot.
!Define_YI_StdObjBE_SewageWaterFlowOutlet = $00BE	; Init Bank12:4933; Stamp Bank13:12280/12368 | Sewage water flowing from a sewage pipe (outlet, variant 0). $15&1 picks CODE_13E583 or CODE_13E62D via DATA_terrain_2variant_complex_stamps. Walker_setup_trampoline. Shared with $BF. CODE_init_terrain_2variant_complex.
!Define_YI_StdObjBF_SewageWaterFlowEdge = $00BF	; Init Bank12:4933; Stamp Bank13:12280/12368 | Sewage water surface (edge, variant 1).
!Define_YI_StdObjC0_SewageWaterFlowLeft = $00C0	; Init Bank12:4948; Stamp Bank13:varies | Sewage flowing left (variant 0). Sets $2E=2. $15&3 picks 1 of 4 stamps from DATA_terrain_4variant_height2_stamps: CODE_13E74C / CODE_13E81D / CODE_13E8A6 / CODE_13E8D9. Variants 0-1 use trampoline; 2-3 use keep_slope. Shared with $C1-$C3. CODE_init_terrain_4variant_height2.
!Define_YI_StdObjC1_SewageWaterFlowRight = $00C1	; Init Bank12:4948; Stamp Bank13:varies | Sewage flowing right (variant 1).
!Define_YI_StdObjC2_SewageWaterFlowDownLeft = $00C2	; Init Bank12:4948; Stamp Bank13:varies | Sewage flowing down-left (variant 2, keep_slope).
!Define_YI_StdObjC3_SewageWaterFlowDownRight = $00C3	; Init Bank12:4948; Stamp Bank13:varies | Sewage flowing down-right (variant 3, keep_slope).
!Define_YI_StdObjC4_CoinHorizontal = $00C4	; Init Bank12 CODE_init_coin_line; Stamp Bank13 varies | Horizontal coin line, placed every 2 blocks (affects item memory). Init splits 6-way on $15 (with $00C7 fence-post adjustment), pre-writes width=1, dispatches via DATA_coin_line_stamps to CODE_stamp_coin_col_aligned/CODE_stamp_coin_row_aligned/CODE_stamp_coin_with_single_row. Shares init with $C5-$C9.
!Define_YI_StdObjC5_CoinVertical = $00C5	; Init Bank12 CODE_init_coin_line; Stamp Bank13 varies | Vertical coin line, placed every 2 blocks. See $C4.
!Define_YI_StdObjC6_CoinDiagonal = $00C6	; Init Bank12 CODE_init_coin_line; Stamp Bank13 varies | Diagonal coin line, placed every 2 blocks (size negative = face left). See $C4.
!Define_YI_StdObjC7_SwitchCoinHorizontal = $00C7	; Init Bank12 CODE_init_coin_line; Stamp Bank13 varies | Horizontal !-switch coin line (collectible only when a !-switch is active). Init bumps $15 by 1 from this slot onward ($00C7 adjustment). See $C4.
!Define_YI_StdObjC8_SwitchCoinVertical = $00C8	; Init Bank12 CODE_init_coin_line; Stamp Bank13 varies | Vertical !-switch coin line. See $C4/$C7.
!Define_YI_StdObjC9_SwitchCoinDiagonal = $00C9	; Init Bank12 CODE_init_coin_line; Stamp Bank13 varies | Diagonal !-switch coin line. See $C4/$C7.
!Define_YI_StdObjCA_SewerWaterPool = $00CA	; Init Bank12:5009; Stamp Bank13:12798 | Sewer water pool (large-LUT stamp). Minimal init, trampoline-walker into CODE_stamp_sewer_water_pool. CODE_init_sewer_water_pool -> CODE_13E9F6.
!Define_YI_StdObjCB_CastleWallEdge = $00CB	; Init Bank12:5016; Stamp Bank13:13085 | Castle wall edge (3-tile, 3-variant). Zeroes $A1, trampoline-walker into CODE_stamp_slope_3tile. CODE_init_slope_3variant_3tile -> CODE_13EBFC.
!Define_YI_StdObjCC_CastleWallDiagonalLeft = $00CC	; Init Bank12:5028; Stamp Bank13:12855/12997 | Upwards left-facing diagonal castle background wall (height 1). Variant 0 of the 2-variant castle-wall-diagonal init (shares CODE_init_castle_wall_diag with $CD); $15&1 selects stamp CODE_13EB64 drawing Map16 tiles $00C9/$00CA/$00C2. Zeroes $A1, sets $17=1. Walker_setup_keep_slope. Shared with $CD.
!Define_YI_StdObjCD_CastleWallDiagonalRight = $00CD	; Init Bank12:5028; Stamp Bank13:12855/12997 | Upwards right-facing diagonal castle background wall (height 1). Variant 1 of the 2-variant castle-wall-diagonal init (shares CODE_init_castle_wall_diag with $CC); $15&1 selects stamp CODE_13EA5A drawing Map16 tiles $00CC/$00CB/$00C2. Walker_setup_keep_slope.
!Define_YI_StdObjCE_LineGuideDiagonal = $00CE	; Init Bank12:5042; Stamp Bank13:13128 | Diagonal line guide (offset variant 1). Hardcodes $15=1 (or $15=0 if $2A<0 i.e. width<0), $17=$FFFF. Walker_setup_keep_slope. CODE_init_col_base_8700_off1 -> CODE_13EC4C.
!Define_YI_StdObjCF_LineGuideDiagonalGradual = $00CF	; Init Bank12:5057; Stamp Bank13:13145 | Diagonal line guide, gradual (offset variant 2, $8702/$8704 pair). Hardcodes $15=2 (or 0 if $2A<0), $17=$FFFF. CODE_init_col_base_8700_off2 -> CODE_13EC66 (CODE_stamp_col_pair_8702_8704).
!Define_YI_StdObjD0_LineGuideDiagonalVeryGradual = $00D0	; Init Bank12:5072; Stamp Bank13:13164 | Diagonal line guide, very gradual (offset variant 3, $8706/$870A pair). Hardcodes $15=2 (or 0 if $2A<0), $17=$FFFF. CODE_init_col_base_8700_off3 -> CODE_13EC81 (CODE_stamp_col_pair_8706_870A).
!Define_YI_StdObjD1_LineGuideVertical = $00D1	; Init Bank12:5087; Stamp Bank13:13184 | Vertical line guide (single-tile $870F). Trivial trampoline. CODE_init_single_tile_870F -> CODE_13ECA1.
!Define_YI_StdObjD2_LineGuideHorizontal = $00D2	; Init Bank12:5094; Stamp Bank13:13190 | Horizontal line guide (single-tile $870E). Trivial trampoline. CODE_init_single_tile_870E -> CODE_13ECA8.
!Define_YI_StdObjD3_RockWall = $00D3	; Init Bank12:5101; Stamp Bank13:13200 | Rock wall / brown rock background (4-tile cycle, $854B family). Trivial trampoline. CODE_init_4tile_cycle_854B -> CODE_13ECB6.
!Define_YI_StdObjD4_RockWallLeft = $00D4	; Init Bank12:5112; Stamp Bank13:varies | Rock wall, left side (variant 0 of 4). Zeroes $A1. $15&3 picks 1 of 4 stamps from DATA_growable_4variant_stamps: CODE_13ED27 / CODE_13EE31 / CODE_13EF57 / CODE_13F06C. Walker_setup_trampoline. Shared with $D5-$D7. CODE_init_growable_4variant.
!Define_YI_StdObjD5_RockWallRight = $00D5	; Init Bank12:5112; Stamp Bank13:varies | Rock wall, right side (variant 1).
!Define_YI_StdObjD6_RockWallCeiling = $00D6	; Init Bank12:5112; Stamp Bank13:varies | Rock ceiling (variant 2).
!Define_YI_StdObjD7_RockWallFloor = $00D7	; Init Bank12:5112; Stamp Bank13:varies | Rock floor (variant 3).
!Define_YI_StdObjD8_LogBridgeGiant = $00D8	; Init Bank12:5128; Stamp Bank13:13783 | Giant log bridge (width 4 from DATA_lift_width_2variant). $15&1 picks width=4 or 3 (writes into $2E); preserves orientation in $15. Walker_setup_trampoline. Shared with $D9. CODE_init_lift_width_select -> CODE_13F167.
!Define_YI_StdObjD9_LogBridge = $00D9	; Init Bank12:5128; Stamp Bank13:13783 | Log bridge (width 3, same init via $15 bit 0).
!Define_YI_StdObjDA_StarBlock = $00DA	; Init Bank12 CODE_init_star_block; Stamp Bank13 CODE_stamp_star_block | Star Mario block (solid only while star power is active).
!Define_YI_StdObjDB_IceFloor = $00DB	; Init Bank12:5152; Stamp Bank13:13819 | Icy floor (random-fill stamp). Trivial trampoline. CODE_init_ice_floor -> CODE_13F1A2.
!Define_YI_StdObjDC_IceFloorEdgeWater = $00DC	; Init Bank12:5159; Stamp Bank13:13867 | Icy floor edges with water between them (3-row lookup-table stamp). Trivial trampoline. CODE_init_ice_floor_edge_water -> CODE_13F206.
!Define_YI_StdObjDD_IceWaterfall = $00DD	; Init Bank12:5166; Stamp Bank13:13942 | Icy waterfall (random-8-phase fill). Init calls CODE_prng + AND #$0007 to store random phase into $15. Walker_setup_trampoline. CODE_init_random_8phase -> CODE_13F2BE.
!Define_YI_StdObjDE_IceWaterfallRock = $00DE	; Init Bank12:5176; Stamp Bank13:14027 | Rock in an icy waterfall (small tile-set, pre-incremented width $2A+=1). CODE_init_small_inc_width -> CODE_13F33B.
!Define_YI_StdObjDF_LavaCavePool = $00DF	; Init Bank12 CODE_init_lava_cave_pool; Stamp Bank13 CODE_stamp_lava_cave_pool | Lava pool (cave) - a pool of lava; hazard.
!Define_YI_StdObjE0_LavaFlowDown = $00E0	; Init Bank12 CODE_init_lava_flow_down; Stamp Bank13 CODE_stamp_lava_flow_down | Downwards-flowing lava (cave); hazard.
!Define_YI_StdObjE1_MushroomPlatform = $00E1	; Init Bank12 CODE_init_mushroom_platform; Stamp Bank13 CODE_stamp_mushroom_platform | Mushroom platform (found in caves).
!Define_YI_StdObjE2_SnowyPlatformSupport = $00E2	; Init Bank12:5216; Stamp Bank13:14209 | Snowy platform support (tall multi-row structure). Sets $2A=4 (4-column-wide template); stamp walks 8+ rows of progressively wider stone tiles. CODE_init_snowy_platform_support -> CODE_13F4E4.
!Define_YI_StdObjE3_IceFloorEdgeHole = $00E3	; Init Bank12:5225; Stamp Bank13:14239 | Icy floor edges with a hole between them. Plain trampoline; caller pre-sets dimensions. CODE_init_ice_floor_edge_hole -> CODE_13F511.
!Define_YI_StdObjE4_FlowerLedge = $00E4	; Init Bank12:5232; Stamp Bank13:14316 | Flower-garden ledge. Normally sized so its width is even.
!Define_YI_StdObjE5_FlowerLedgeDownLeftGradual = $00E5	; Init Bank12:5256; Stamp Bank13:14399 | Flower-garden ledge: gradual downward slope facing left.
!Define_YI_StdObjE6_FlowerLedgeDownLeft = $00E6	; Init Bank12:5266; Stamp Bank13:14475 | Flower-garden ledge: average-grade downward slope facing left.
!Define_YI_StdObjE7_FlowerLedgeDownLeftSteep = $00E7	; Init Bank12:5276; Stamp Bank13:14520 | Flower-garden ledge: steep downward slope facing left.
!Define_YI_StdObjE8_FlowerLedgeDownRightGradual = $00E8	; Init Bank12:5296; Stamp Bank13:14582 | Flower-garden ledge: gradual downward slope facing right.
!Define_YI_StdObjE9_FlowerLedgeDownRight = $00E9	; Init Bank12:5306; Stamp Bank13:14683 | Flower-garden ledge: average-grade downward slope facing right.
!Define_YI_StdObjEA_FlowerLedgeDownRightSteep = $00EA	; Init Bank12:5316; Stamp Bank13:14728 | Flower-garden ledge: steep downward slope facing right.
!Define_YI_StdObjEB_FlowerLedgeEdgeLeft = $00EB	; Init Bank12:5336; Stamp Bank13:14781 | Left edge of a flower-garden ledge.
!Define_YI_StdObjEC_FlowerLedgeEdgeRight = $00EC	; Init Bank12:5336; Stamp Bank13:14781 | Right edge of a flower-garden ledge.
!Define_YI_StdObjED_Stone3DWall = $00ED	; Init Bank12 CODE_init_stone_3d_wall; Stamp Bank13 CODE_stamp_stone_3d_wall | 3D stone wall (size it negatively for correct appearance).
!Define_YI_StdObjEE_Stone3D = $00EE	; Init Bank12 CODE_init_stone_3d; Stamp Bank13 CODE_stone_3d_stamp | Static 3D stone (per GoldenEgg: bottom hollow). Init CODE_init_stone_3d derives $A1 from XOR of $1B and $1B>>4 (map-grid parity) and $15 from ($15&1) XOR 1, then trampolines into CODE_stone_3d_stamp. Differs from the moving 3D stones $F0-$F3 by NOT registering an OPTMovingObjectTable entry. Shares init with $EF.
!Define_YI_StdObjEF_Stone3DSolidBottom = $00EF	; Init Bank12 CODE_init_stone_3d; Stamp Bank13 CODE_stone_3d_stamp | Static 3D stone (per GoldenEgg: bottom solid). Same init (CODE_init_stone_3d) as $EE; see $EE notes.
!Define_YI_StdObjF0_Moving3DStoneSlow = $00F0	; Init Bank12 CODE_init_moving_stone_3d; Stamp Bank13 CODE_stone_3d_stamp | Moving 3D stone, slow (amplitude $20 = +slow, from DATA_moving_stone_3d_amplitudes[0]). Builds a 6-byte {leftTileX, topTileY, $2A-1, $2E-1, amplitude} record and registers it in the 3D-object render table OPTMovingObjectTable at $70:449E (6-byte stride, up to 20 slots), sets $15=$8000, derives $A1, then stamps the column via CODE_stone_3d_stamp. The entry is animated by the SuperFX 3D renderer CODE_02C1F4 (shared with Nep-Enut, sprite $A5). Variants $F1-$F3 share this init with different amplitudes.
!Define_YI_StdObjF1_Moving3DStoneQuick = $00F1	; Init Bank12 CODE_init_moving_stone_3d; Stamp Bank13 CODE_stone_3d_stamp | Moving 3D stone, quick (amplitude $40 = +quick). See $F0.
!Define_YI_StdObjF2_Moving3DStoneSlowReverse = $00F2	; Init Bank12 CODE_init_moving_stone_3d; Stamp Bank13 CODE_stone_3d_stamp | Moving 3D stone, slow, reverse direction (amplitude $E0 = -slow). See $F0.
!Define_YI_StdObjF3_Moving3DStoneQuickReverse = $00F3	; Init Bank12 CODE_init_moving_stone_3d; Stamp Bank13 CODE_stone_3d_stamp | Moving 3D stone, quick, reverse direction (amplitude $C0 = -quick). See $F0.
!Define_YI_StdObjF4_PipeVerticalNotEnterable = $00F4	; Init Bank12:3468; Stamp Bank13:varies | Unenterable vertical pipe (SHARED with $3C). Masks $15 to bit 7 (orientation), sets $2A=$0002 (forces 2-column footprint), dispatches to CODE_pipe_vertical_dispatch. CODE_init_pipe_vertical.
!Define_YI_StdObjF5_SpikeArea = $00F5	; Init Bank12 CODE_init_spike; Stamp Bank13 CODE_stamp_spike | Spike area (kills Yoshi instantly). Two-tile vertical column: $8413 cap (tip) + $2910 body (shaft).

!Define_YI_StdObjF6_KamekRoomBlock = $00F6	; Init Bank12:5486 (CODE_init_decoration_overlay); Stamp Bank13: (CODE_decoration_overlay) | Block in Kamek's room: paints Map16 $9D8B only on cells that are currently empty ($0000), never overwrites existing terrain. Thin trampoline-only init. **Final entry in DATA_standard_object_init_ptrs** (247 entries total, rows $00-$F6).
