;#############################################################################################################
;# PlayerStates.asm -- Yoshi player-state machine plus transformation forms.
;#############################################################################################################

!Define_YI_PlayerState00_Normal = $0000	; Normal gameplay: Yoshi accepts full input (move/jump/egg-throw/tongue/duck/ground-pound). Default in-level state; FreeMovement debug toggle lives here. Falls into PlayerState1A_DisableInput when level Y-pos passes the death-pit threshold.
!Define_YI_PlayerState02_InCutscene = $0002	; In-cutscene/scripted-movement: Yoshi is frozen; $617A/$617C drive the SuperFX-side animation frame and the engine just blits whatever the script preloaded. Used as the resting state during boss-room arrivals, world-map cutscenes, and post-key-grab waits.
!Define_YI_PlayerState03 = $0003	; Sentinel value, not a real dispatch slot (table only has 22 entries). Used by Bank03's hit handler as the "can-be-hurt" cutoff: if Yoshi_CurrentState >= $03, BCS skips sprite-hit; states $00 and $02 are the only ones that take damage.
!Define_YI_PlayerState04 = $0004	; Generic locked-input cutscene driver used by miscellaneous scripted sequences (e.g. Welcome-Level intro pan). Steps a $617E sub-counter, walks Yoshi rightward via $60A8/$60AA, switches to GameMode0B (next-level boot) when the X-pos passes a threshold.
!Define_YI_PlayerState06 = $0006	; Pipe-entry / pipe-traversal: started when Yoshi enters a pipe entrance. Pulls Yoshi into the warp via per-direction tables (DATA_04E437/$E43B/$E43F), runs the in-pipe walk animation, then transitions to PlayerState08 (pipe exit) or back to $00.
!Define_YI_PlayerState08 = $0008	; Pipe-exit / under-block emergence: probes the Map16 cell at Yoshi's feet via FXCODE_0ACE2F, opens key blocks if a Key sprite is overhead (calls CODE_change_map16), then drops into PlayerState06 to finish the pipe walk.
!Define_YI_PlayerState0A_EnteringDoor = $000A	; Entering door: animates the door-open SuperFX sprite stamp (FXCODE_08AA7F), walks Yoshi through frames in DATA_04F8D1, palette-fades, and switches map via CODE_02A4B5 when fully entered. Also the entry path that swaps to Skiing form (PlayerForm0E) on icy levels.
!Define_YI_PlayerState0C = $000C	; Knocked off cliff / pit-bump: locks Yoshi's horizontal speed to $0300 left, clamps Y-pos to the screen, and auto-returns to PlayerState00_Normal once horizontal scroll $60B0 < $0020. Brief stagger animation, no input.
!Define_YI_PlayerState0E_TouchedSpike = $000E	; Touched-spike bounce-back: shared with the lava state for the airborne knockback arc. Walks Yoshi through DATA_04F7AE timing table and DATA_04F7E8 animation frames; on stop, switches GameMode to "lose-Baby-Mario" via CODE_04F6CE.
!Define_YI_PlayerState10_Transforming = $0010	; Mid-transformation: drives the multi-frame magic-bubble morph sequence between forms. Reads $0C8A (target form), runs FXCODE_08B4A9/$08BA44 pixel-mixing FX, calls DATA_transform_finalize_ptr to scrub form-specific WRAM, then exits to PlayerState00 in the new form.
!Define_YI_PlayerState12_SmushedByWall = $0012	; Smushed-by-wall death: Yoshi is crushed flat between converging walls. Plays YoshiLostChallenge, snaps Y-pos up $0008, animates the smush via FXCODE_08C136 with a 0x79-frame timer; resets to PlayerState00 when the death sequence completes (or hands off to lose-Baby-Mario).
!Define_YI_PlayerState14_ActivateGoal = $0014	; Activate-goal: Yoshi reached the level goal ring/roulette. Pure rendering tick -- zeros $6070/$6072 hold flags and calls SuperFX RT FXCODE_0BC6E7 for the goal-spin VRAM update. Game-mode change happens elsewhere; this slot just keeps Yoshi posed.
!Define_YI_PlayerState16_LevelIntro = $0016	; Level-intro pan: Yoshi descends from off-screen at level start. Animates $60AA fall, snaps to floor when Layer1Y+$94 meets Yoshi-Y, clears $60C0 ground flag, transitions out via $61D4 timer-driven side path.
!Define_YI_PlayerState18_SentTowardsBabyMario = $0018	; Sent-toward-Baby-Mario (Star powerup ran out): Yoshi homes onto the floating Baby Mario sprite at ($70E2,$7182). Form is force-reset to $00 (Yoshi), SuperFX MULT lerp pulls position toward target, then returns to PlayerState00 once X+Y both match.
!Define_YI_PlayerState1A_DisableInput = $001A	; Disable-input stub: pure RTS. Yoshi is frozen with no animation update. Used while sprite scripts (Piranha grab, fall-to-death) drive his position directly. State must be cleared externally.
!Define_YI_PlayerState1C_Prologue = $001C	; Prologue state: zeros $611A (carry-stack count) then falls into the disable-input RTS at $04F849. Used during the storybook prologue cinematic so Yoshi shows no animation while text scrolls.
!Define_YI_PlayerState1E_PushedAwayByRaphael = $001E	; Pushed-away-by-Raphael: post-defeat bounce after the Raphael Raven fight. Per facing-flag in $60FC, sets $60A8/$60AA to (+$0800,-$0400) or (-$0400,-$0800), clamps to screen, calls CODE_02A4B5 to load the next room.
!Define_YI_PlayerState20_EnteringRaphaelBossRoom = $0020	; Entering-Raphael-boss-room: scripted fall onto the moon. Plays SoundID89_FallingToMoon, decelerates $617E from $0800 down to $0100, runs FXCODE_0A91C9 / $08B2B2 / $088205 / $08E167 pipeline to position+palette-blend Yoshi onto the moon, then locks to PlayerState02.
!Define_YI_PlayerState22_EnterKeyhole = $0022	; Enter-keyhole (post-key bonus): keyhole-warp screen-fade. Increments hold $61B4, masks $6070 to $0100 + $6084 fade tint, drives SuperFX RT FXCODE_0BC703 + $0BC6EF for the keyhole zoom transition.
!Define_YI_PlayerState24 = $0024	; Pipe-exit pop-up: vertical emergence with the bounce. Decrements $6180 timer ($0040..$00) for the pop-out arc, then drops to PlayerState02_InCutscene; if $60C0 ground flag set, increments anim $6182 up to $00DD.
!Define_YI_PlayerState26 = $0026	; Player ride-script: scripted movement reading commands from DATA_04E005 ($02,$08 etc. = move-X-Y opcodes with $FF terminator). Used for Yoshi-on-cinematic-platform sequences; reads per-step deltas and ends at $07A0 Y-floor.
!Define_YI_PlayerState28_TouchedLava = $0028	; Touched-lava: lava-burn death sequence. Spawns AmbSpr1DF (burn-fizz), runs the rising arc via $60AA -$28 per frame clamped to $0400, transitions to lose-Baby-Mario (CODE_04F6CE) when X-scroll $60B2 >= $0120.
!Define_YI_PlayerState2A = $002A	; Bouncing back from pipe-block: stripped variant of state $26 that resets $617A/$617C, then either falls into PlayerState02 if $60C0 still set, or clears CurrentState to $00 (Normal) and unfreezes sprites.

!Define_YI_PlayerForm00_Yoshi = $0000	; Yoshi (base form): standard 4-button platforming. Carries Baby Mario, throws eggs (B), tongues+swallows enemies (Y), ground-pounds (A+down), flutter-jumps (hold B). Default form on level entry; CODE_transform_finalize_yoshi_or_mushroom_noop runs on entry (no-op).
!Define_YI_PlayerForm02_Car = $0002	; Car (Mario Block): treads-rolling 2-wheel car with auto-jump. Limited control -- B/A trigger a hop; the form auto-drives forward at constant speed. CODE_transform_finalize_car_full_reset zeroes ~22 form WRAM slots ($617E-$61E4) on entry and exit.
!Define_YI_PlayerForm04_Mole = $0004	; Mole (Mole Tank): tunnels through diggable terrain (Map16-driven). Y-axis input dives down/up; X is auto-drive. Brief invulnerability while underground. CODE_transform_finalize_mole clears $617E/$6180-$618A on entry/exit.
!Define_YI_PlayerForm06_Helicopter = $0006	; Helicopter (Helicopter Yoshi): vertical-rising propeller form on a hold-timer. Hold B to ascend (timer in $61F6); X-axis lets you drift side-to-side. CODE_transform_finalize_helicopter zeroes $617E/$6182/$6184/$61F6 on entry/exit; timer-driven auto-revert at zero.
!Define_YI_PlayerForm08_Train = $0008	; Train (Train Yoshi): rail-locked form running on Map16-laid track tiles. Direction bit preserved in $617E sign (via $60C4 -> $8000 mask in CODE_transform_finalize_train). Track switches at junction tiles; cannot leave the rails.
!Define_YI_PlayerForm0A_Mushroom = $000A	; Mushroom (Mushroom Yoshi): underground/cave drilling form (visually different from Mole but mechanically similar -- enters via a different magic block). Uses the same CODE_transform_finalize_yoshi_or_mushroom_noop entry no-op as base Yoshi.
!Define_YI_PlayerForm0C_Submarine = $000C	; Submarine (Submarine Yoshi): underwater-mode 4-direction swimmer with torpedoes. Free 8-direction movement; B fires forward-arc torpedo, A bobs/dives. CODE_transform_finalize_submarine just zeroes $617E on entry.
!Define_YI_PlayerForm0E_Skiing = $000E	; Skiing (Ski Lift / Sled Yoshi): downhill auto-slide on icy levels. Triggered from PlayerState0A (door-entry) when $0C8C set + level $C8 (icy). X-input steers; gravity drives downward. Used in 5-1 Danger-Icy-Conditions and 6-4 Kamek's Revenge.
!Define_YI_PlayerForm10_SuperBabyMario = $0010	; SuperBabyMario: invincible Mario-running mode triggered by Super Star sprites ($059/$088). 10-second timer ($61F4) of full-speed run, all hazards disabled, no Yoshi sprite drawn. Reverts via PlayerState18_SentTowardsBabyMario homing-back path.
!Define_YI_PlayerForm12_Plane = $0012	; Plane (Plane / Vehicle Yoshi): horizontal-flight form. Used in Touch Fuzzy/Helicopter-style auto-scroll segments and the 6-Castle plane segment. Auto-drives forward; X/Y inputs steer cardinally; B fires.
